### ISSUE TITLE
Interactive logon message not audited properly

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#100]
Situation on WIndows Server 2019 machine - interactive logon message and title empty

![image](https://user-images.githubusercontent.com/23223285/165122571-42105be1-6f4a-4e71-b4c5-f16269ff27b9.png)

Result in audit: 

![image](https://user-images.githubusercontent.com/23223285/165122674-a081ad4b-451c-4d3d-972d-1f18e784bd34.png)

**Expected behaviour**
As an interactive logon message in recommended by CIS it should be properly checked and audited. The actual situation seems to be misinterpretation of an empty registry key.

**Comment by SteffenWinternheimer** [comment]
Fixed Issue with commit dedeb068353021ade2a3397dadc27cfa32af0934
