### ISSUE TITLE
Some checks have issues with localized group names

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#101]
Example: DISA WN10-AU-000525 expects English names (BUILTIN\Administrators) and fails with German names (VORDEFINIERT\Administratoren) though they are technically the same.
Please change this (and all other similar checks) to use SIDs rather than names to make this universally valid.

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed with commit b1f7062deed106d14f59e4956abbff721bfaea4b
