### ISSUE TITLE
Imprecise Taskdescriptions

### ISSUE THREAD

**Issue by qngngyn** [fbprogmbh/Audit-Test-Automation#102]
![image](https://user-images.githubusercontent.com/104337428/165920922-ae595e75-b6c3-40fc-b9ef-9b3af305a09c.png)

In Microsoft Benchmarks (around Registry 97-127), taskdescription are not divided in their categories: Domain, Private and Public (all look the same but are different registries).

**Comment by TuemmlerKelch** [comment]
Found another instance in BSI Benchmark:
![image](https://user-images.githubusercontent.com/68649859/168798197-d8978358-1be4-451f-9494-42ec6e715f5a.png)

**Comment by TuemmlerKelch** [comment]
This task name should actually be "enabled" not "disabled"
![image](https://user-images.githubusercontent.com/68649859/168798442-1c3bf8c4-3cdf-423d-9be9-08ce71b5529d.png)
