### ISSUE TITLE
Windows 10 Report > BSI 273 falsely reported as incompliant

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#105]
I believe this is checking if the Value "Optional" is blank (under HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\SubSystems)
Even though there are no entries, it is reporting **Registry value is ''. Expected:** . However I believe it should be reporting true.

The same goes for BSI Benchmarks SiM-08202 - BPOL --> 0323 & 0324
(Please understand and fix the underlying issue everywhere, not only in the above in case there are more occurrences I might have missed)

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed for the next version
