### ISSUE TITLE
v5.0 on Windows11 CIS 1.0.0 "cannot bind argument to parameter 'Name' because it is an empty string."

### ISSUE THREAD

**Issue by qngngyn** [fbprogmbh/Audit-Test-Automation#106]
![grafik](https://user-images.githubusercontent.com/104337428/167092983-60756f2f-a24a-461b-bd83-65cebcd74b80.png)

Additionally unknown whether it is due to this exception:
ATAP Html Creation does not finish as seen in the screenshot above (stuck at this point).
The html sheet seems to have been created though - so not sure what that means.

**Comment by flobroeder** [comment]
Please check in next version and open ticket again in case it is needed.

**Comment by qngngyn** [comment]
Issue fixed with 7f75fd504d975f5a1918920b8288455c5c3b7ab3
