### ISSUE TITLE
ASR rule naming in NCSC benchmark not clear AND validation seems incorrect

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#109]
1) Naming is not clear which ASR rule is meant here - please adopt to new CIS naming convention for ASR rules.
2) The validation show "false" in CyberGovAU section , but in same Windows 10 report CIS and Microsoft validation show "true"...this seems to be an validation error...

![image](https://user-images.githubusercontent.com/23223285/168563385-27889c9e-ecb5-4c5d-9586-c10a59b8abb2.png)

**Comment by SteffenWinternheimer** [comment]
Issue should now be fixed with latest commit [03711bb](https://github.com/fbprogmbh/Audit-Test-Automation/commit/03711bbb346c4bbee2bab1d408ad6ea1370260f4). Bug will disappear in next update.
