### ISSUE TITLE
Add feature: ASR rules detail in Security Base Data part

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#112]
I think it would be nice to get an overview on the status of all the ASR rules and their configuration as extension for the security base Data.

Something like this:
https://github.com/anthonws/MDATP_PoSh_Scripts/blob/master/ASR/ASR_Analyzer_v2.2.ps1

Also, please give the exact count on how many ASR rules are activated and not "less than 12" or similar phrases.
Something like this: "X ASR rules are activated. Less than 12 > Warning, less than Y > False)"

**Comment by qngngyn** [comment]
Updated with c9bbe821bce200a9ad484f84dd681b5b21b4dd48
