### ISSUE TITLE
Error when generating Windows Server 2022 Report

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#113]
System: Server 2022 Datacenter (21H2 Build 20348.768) VM hosted on Hyper-V

When creating the report, I receive the following error. Report is generated, though.
Probably related to "_SBD-002: Ensure the system is using SecureBoot_", as I receive an error, there.
![image](https://user-images.githubusercontent.com/68649859/176715248-6e3205f2-aafe-42f8-b7c8-c224d2b2e0ba.png)

Further analysis done by @qngngyn shows that this is related to the VM this was tested on being a Generation 1 Hyper-V VM and thus not being UEFI compatible.

**Comment by qngngyn** [comment]
Has been fixed with de880c360dd0f8c2bce663a338a96542a37e976a
