### ISSUE TITLE
Windows Security Base Data not supported in older versions

### ISSUE THREAD

**Issue by qngngyn** [fbprogmbh/Audit-Test-Automation#118]
Reports that are not compatible with SBD currently found: Windows Server 2019 and Windows Server 2016
Compatibility is not given, due to lack of Cmdlets in older versions that are used in SBD. Needs further Work, and if needed Errorhandling.

Screenshot from Windows Server 2016:
![grafik](https://user-images.githubusercontent.com/104337428/180443464-77ef3279-d971-4e1d-a6bc-4d5415d0ea97.png)

**Comment by TuemmlerKelch** [comment]
Could not reproduce with Server 2019, please provide further information on used PS version etc.

**Comment by TuemmlerKelch** [comment]
Please provide a list of necessary cmdlets and which OSversions are lacking which. For the first iteration, I suggest adding a transparent error message as result in corresponding controls in the report.

**Comment by SteffenWinternheimer** [comment]
clarify internally and retest.

**Comment by SteffenWinternheimer** [comment]
Fix Issue with commit [a5c3ce2](https://github.com/fbprogmbh/Audit-Test-Automation/commit/a5c3ce2dffeb588464e1b8af580a68864294f22f)
