### ISSUE TITLE
Remove duplicate files from installer folder

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#120]
Below file/Folders are already present in root folder:
/Audit-Test-Automation/Installer/LICENSE
/Audit-Test-Automation/Installer/Audit-Test-Automation/

if there are any references, make sure to point to root folder now.

**Comment by SteffenWinternheimer** [comment]
Issue fixed with commit f9bf54816b5a680c7c4133aa27e5fe50e515f183
