### ISSUE TITLE
Server 2022 and Windows 11 audit groups have invalid checks

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#122]
Please update audit groups to implement fixes to those benchmarks.
ASR rules were pointing to wrong registry key
printer rules had double space in registry path
etc

**Comment by SteffenWinternheimer** [comment]
AuditGroups have been updated with commit 82f331b73e90e26eb41a1d5f9dcdd7e2eed75a0c and e191e1e2255d0688b55d791afbedea74134ee170
