### ISSUE TITLE
Errors in PowerSHell command windows when creating WIndows 11 report on german WIndows 11

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#125]
![image](https://user-images.githubusercontent.com/23223285/188469710-6958c336-a7dd-42f2-a2cc-3cc9b894f0fe.png)

**Comment by SteffenWinternheimer** [comment]
@flobroeder  could you please provide more information? Something like a screenshot of the SBD area of the report would be helpful to find the issue more quickly :)

**Comment by flobroeder** [comment]
Need to be investigated - not reproducable so far...

**Comment by SteffenWinternheimer** [comment]
No errors occured while creating Report. Issue closed for now.
