### ISSUE TITLE
Wrong registry value name in various benchmarks

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#126]
Various benchmarks check the valuename **LSAAnonymousNameLookup** under **HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa** to be **0**

While the key is correct, the valuename should be **TurnOffAnonymousBlock** an valuedata **1**

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed with commit [048f06e](https://github.com/fbprogmbh/Audit-Test-Automation/commit/048f06ecacfcf4e5afe80a41f1e6d231e8308691)
