### ISSUE TITLE
Transparency > Security Base Data

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#128]
For more transparency, please implement the following checks to follow the screenshot
- SBD-009
- SBD-010
- SBD-021

![image](https://user-images.githubusercontent.com/68649859/188592486-2ad33838-3b3d-4120-9492-ef192afcbcfa.png)

[ASR rules overview](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide)

**Comment by SteffenWinternheimer** [comment]
Solved enhancement with commit [11f5ae9](https://github.com/fbprogmbh/Audit-Test-Automation/commit/11f5ae9537dd0e3232c9da038c83680aec4a77f2)
