### ISSUE TITLE
Missing "h2" headline in Settings overview Sections // typo

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#131]
1) Missing structure/headline in "Settings overview" tab as agreed. Please add a headline between "table of contents" and the first benchmark details...

![image](https://user-images.githubusercontent.com/23223285/188951744-4648f5df-4ab8-4a99-82be-3598d17f92fb.png)

2) Call it table of contents , in concrete add "s"...

![image](https://user-images.githubusercontent.com/23223285/188951670-ffda3fb3-73ca-41ae-93a0-feaee1faf381.png)

See screenshot...

**Comment by SteffenWinternheimer** [comment]
Enhancement has been implemented. Will be included in next Release.
