### ISSUE TITLE
Please add column severity on "risk score" overview in order to make transparent that settings are rated

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#132]
Add a column "severity" with content "critical" in order to make severity transparent...

![image](https://user-images.githubusercontent.com/23223285/189049562-28d392f4-c172-4842-bcdf-ec6bbf6b2e6b.png)

Thanks to Trovent Security Gmbh!

**Comment by SteffenWinternheimer** [comment]
Enhancemend has been implemented. Will be added in next release.
