### ISSUE TITLE
AuditTAP preview 3 crashes on german Windows 11 when using installer and CMD menu to create WIndows 11 report

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#133]
Reproduction
Use installer and report "18" on a german windows 11

![image](https://user-images.githubusercontent.com/23223285/189102072-6975a994-f21f-475f-bffd-bbd0dbdb4612.png)

Please check if SIDs are used and english names are not hard coded...

**Comment by SteffenWinternheimer** [comment]
Fix issue with commit [1582d6e](https://github.com/fbprogmbh/Audit-Test-Automation/commit/1582d6eb7e4be4b3ae510338578cbd4479f04f42)
