### ISSUE TITLE
Hardened UNC paths for SYSVOL and NETLOGON are reported as false in MS section

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#134]
The result is seen below:
Registry value is 'RequireMutualAuthentication=1, RequireIntegrity=1'. 
Expected: RequireMutualAuthentication=1,RequireIntegrity=1

As both is technically correct, please allow both versions (with and without blank)

**Comment by SteffenWinternheimer** [comment]
Fixed with commit [29666b8](https://github.com/fbprogmbh/Audit-Test-Automation/commit/29666b851484cbae371ef4c8ed31eddcaa5cc185)
