### ISSUE TITLE
AuditTap crashes 

### ISSUE THREAD

**Issue by Hamburger-It-Service** [fbprogmbh/Audit-Test-Automation#135]
![image](https://user-images.githubusercontent.com/110817119/189321296-c4e0b5cb-bc40-4ba6-b7ba-bb840aea0742.png)

Tested  on Windows 11 German

**Comment by flobroeder** [comment]
Root cause have been orphaned accounts in "local administrators" group. 
Accounts deleted, works like a charme.

**Comment by flobroeder** [comment]
We should think about another solution and check for "orphaned accounts" anywhere accounts are used...
We had another system with orphaned accounts and AuditTAP shows red error in PowerShell session - created reports shows "error"...

![image](https://user-images.githubusercontent.com/23223285/189690701-2d6d77ce-823a-4e7e-95c3-a395fdbfd564.png)

![image](https://user-images.githubusercontent.com/23223285/189690824-66c1c195-1d17-4876-863d-1e0499bb9eb9.png)

**Comment by SteffenWinternheimer** [comment]
Duplicate to issue https://github.com/fbprogmbh/Audit-Test-Automation/issues/158
