### ISSUE TITLE
ASR rules are not checked correctly

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#136]
Repro:
Create PreRelease 4 report, check "Security Base Data" -> ASR fine
THen check CIS details -> ASR rules "non compliant"

![image](https://user-images.githubusercontent.com/23223285/189327106-5f3fadf3-b650-473b-b476-9d4e730baada.png)

**Comment by SteffenWinternheimer** [comment]
Fixed Issue in commit a97a5b2e525a364717adf6fc1f39f2f3837015aa
