### ISSUE TITLE
SecureBoot validation in MS Security Baseline not correct

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#137]
Repro
1) Activate SecureBoot 
2) Create AuditTAP
3) Check MS Security Baseline ID Registry-025 - leads to "false" although it is enabled

Please check validation rule.

![image](https://user-images.githubusercontent.com/23223285/189327596-d2735237-3e47-451f-a6dd-aa337208b95a.png)

**Comment by qngngyn** [comment]
Fix with 9f9cf344fb226be7b2258421ee5738b31670f074
