### ISSUE TITLE
MS Security Baseline Issue - same setting in two different checks? 

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#138]
Please check:
![image](https://user-images.githubusercontent.com/23223285/189332351-ac283d8b-c6b6-4f71-b53f-01a1e89fd812.png)
![image](https://user-images.githubusercontent.com/23223285/189332386-37ca3565-0fa0-4bfe-916a-9190ba2319c8.png)

**Comment by SteffenWinternheimer** [comment]
Issue fixed.
