### ISSUE TITLE
MS Security Baseline states "false" although its better than expected

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#139]
![image](https://user-images.githubusercontent.com/23223285/189333299-a246978c-87cf-40d7-88d5-927314b57406.png)

**Comment by flobroeder** [comment]
![image](https://user-images.githubusercontent.com/23223285/189333381-d1e422e9-dc86-4f14-b6f5-46fe8bc00ca7.png)

**Comment by qngngyn** [comment]
Fix with d31fff240547911e345bb62c78185d97b9ea3636

**Comment by flobroeder** [comment]
Please check for other "DENY" rules...

**Comment by qngngyn** [comment]
Fixed with 3822b73b656c1aed8fb564e8cc3db914ff49cf8e
Largescale change into all "Deny"-rules.
