### ISSUE TITLE
"Prohibit connection to non-domain networks when connected to domain authenticated network" not checked correctly

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#140]
AuditTAP report states "False" in different sections although setting is set correctly

![image](https://user-images.githubusercontent.com/23223285/189334338-646019f8-fef8-4c5a-9679-865005da6e47.png)

![image](https://user-images.githubusercontent.com/23223285/189334478-6b24f4e0-955c-43a7-bc07-91a5bdf6f662.png)

More details: https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsConnectionManager::WCM_BlockNonDomain

**Comment by qngngyn** [comment]
Detail on Key is different to hardening setting.
ATAP works correctly, mismatch of hardening setting and hardening recommendation.

Following is the corresponding hardening setting to the ATAP Output 'False':
https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsConnectionManager::WCM_MinimizeConnections

**Comment by flobroeder** [comment]
Thanks for clarification @qngngyn - we still need to adress this topic. Following update: 

Addtional setting is set to 3 now: 

![image](https://user-images.githubusercontent.com/23223285/189646109-a3730300-5304-4a3e-8bf5-a9293de9b948.png)

AuditTAP complains now and states "non compliance": 
![image](https://user-images.githubusercontent.com/23223285/189645891-66000c61-76af-4af0-9791-2683b55329cb.png)

Please update AuditTAP compliance check routine to only state "non compliance" when nothing or "0" is configured.
In case 1 or higher is configured it is "compliant".
Following your provided link https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsConnectionManager::WCM_MinimizeConnections

**Comment by qngngyn** [comment]
Fixed with 
2fdc81d53c705353e211b60bb0571398faeda3ac
9b256bcc732661c27ea878fc05f627344b15d5a1 
326315d588c34f93cbc52ee24f165ab87bb83582
