### ISSUE TITLE
ASR rule (MS Benchmark) - AuditTAP states "false" although it is enabled...

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#144]
**Powershell extract:** 
![image](https://user-images.githubusercontent.com/23223285/189649192-b79feae8-976b-4aa7-98d2-38e701ad7d86.png)

**AuditTAP report:** 
![image](https://user-images.githubusercontent.com/23223285/189648953-f0cf3a2b-5b0c-4f0d-b603-6e6226397ead.png)

Please check for validation logic...

**Comment by TuemmlerKelch** [comment]
This one was missed with #136

**Comment by qngngyn** [comment]
Fixed with f3b8936723cfe2ca6d90f1ddaf2b69f0872c62bb
Additional Test-IDs that were fixed: "1909.03.10", "Registry-039", "Registry-306"

**Comment by flobroeder** [comment]
Sorry for reopening - still not solved...

**Comment by qngngyn** [comment]
Fixed with
853846c73587d775dd290321f44a39c82a63646f
3867717c33cd46b9574fbc89cf4bf3b1538ad1c1
