### ISSUE TITLE
Non-existent registry key for DisableRealtimeMonitoring leads to FALSE

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#146]
Currently we are looking for "0", but if this registry-entry does not exists, this has the same effect. So please check for "0" or non-existence of the valueName.
![image](https://user-images.githubusercontent.com/68649859/189678631-3af041eb-714d-447e-aa71-e204e98b768c.png)

**Comment by qngngyn** [comment]
Fixed with 9ef2d3ec2a039b8319a44ea1bcbf42ca824597cc
