### ISSUE TITLE
ASR rules are only active while Defender is in active mode

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#147]
Simply checking for ASR rules will yield a TRUE, even when defender is in passive mode.
Please add a check to verify Defender is running in Active mode before counting this as true:

`Get-MPComputerStatus | Select AMRunningMode`

If this returns `Normal`, Defender is running in active mode
ELSE
Defender is running in passive mode or passive mode with EDR in Block mode and ASR rules are not processed.
This should result in false with an appropriate message like ASR rules are only active if Microsoft Defender is in active mode. Please ensure your 3rd party Anti Virus offers similar functions.

[ASR rules dependencies](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment?view=o365-worldwide#asr-rules-dependencies)

**Comment by qngngyn** [comment]
Fixed with d7b38b429dd0f6b9a69f06173c3a46934c8edc06
