### ISSUE TITLE
TPM is not present on VM-Ware

### ISSUE THREAD

**Issue by Hamburger-It-Service** [fbprogmbh/Audit-Test-Automation#148]
TPM is not configured on the tested Windows on the vmware.
Please improve code. Status now is Error, correct is false.
see picture
![image](https://user-images.githubusercontent.com/110817119/189850206-3ef2aba6-ed6e-4e9f-9317-8a79ef9f2752.png)

**Comment by qngngyn** [comment]
Fix with 0a5c079b59efe9169362eb4eab1bcd69637c13ff
