### ISSUE TITLE
Optimize rule validation

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#150]
Rule requires "LockoutBadCount" 10 - actual confiuguration is "5" - far better than required. 
Should be check for settings not equal 10 but equal or lower 10...

![image](https://user-images.githubusercontent.com/23223285/190188473-74b440a8-1f2c-4003-bc6f-65799f1d1028.png)

**Comment by qngngyn** [comment]
Fixed with 32ca00f5aa83555384733a91dff92693876c3c96 (above fixes were wrong, misunderstanding but cleared up)
