### ISSUE TITLE
Security Base Data Enhancement

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#154]
SBD-008 is to be rated as 'False' when there is no TPM
SBD-009 Return amount of local users in 'Message'-Field

**Comment by qngngyn** [comment]
Mistake in last commit, fixed here: 22268703c1973fe16f11ee64ce8f04501c49e45c

**Comment by SteffenWinternheimer** [comment]
If TPM does not exist, it's not needed to make the other tests.
![grafik](https://user-images.githubusercontent.com/35689334/195040305-a364eea4-749a-4860-a732-e32e4b48f72c.png)

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed with commit [bbf9a03](https://github.com/fbprogmbh/Audit-Test-Automation/commit/bbf9a03a3226c525862f88d6fab2876d739a3ec0)
