### ISSUE TITLE
DISA rules show "false" checking Event Log size

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#156]
Please check validation of the following rules - rules seem to be configured correctly but AuditTAP leads to "non compliance":

![image](https://user-images.githubusercontent.com/23223285/191959077-2423f3cc-a13a-4f4e-8d67-d92c79f8121b.png)

**Comment by flobroeder** [comment]
Tried to investigate: above mentioned rules do not appear in Win Server 2019 report. Need to get more information...

**Comment by TuemmlerKelch** [comment]
Steffen, please find out, why DISA 1.2 is still used. Audit groups for 1.5 are present and we state DISA 2019 to be on Version 1.5

**Comment by SteffenWinternheimer** [comment]
Check via POwerShell and not registry "Get-Eventlog -List" following 

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-eventlog?view=powershell-5.1

**Comment by SteffenWinternheimer** [comment]
Issue closed for now. Current Version of AuditGroups don't check these rules.
