### ISSUE TITLE
Windows 11 audit Report SBD error with AzureAD Account SIDs

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#158]
Due to a bug in Get-Localgroupmember command, we receive the following error:

Reference: https://github.com/PowerShell/PowerShell/issues/2996
possible Workaround:
$group = Get-LocalGroup -sid "S-1-5-32-544"
$group = [ADSI]"WinNT://$env:COMPUTERNAME/$group"
$group_members = @($group.Invoke('Members') | % {([adsi]$_).path})
$group_members

![image](https://user-images.githubusercontent.com/68649859/192749377-a539b401-2c54-4109-a94f-e5e595c460d5.png)

**Comment by SteffenWinternheimer** [comment]
https://learn.microsoft.com/en-us/answers/questions/423013/find-account-or-group-from-sid-in-local-administra.html

make a loop, which catches SIDs with starting value "S-1-12-1" (AzureAD accounts)

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed with commit [6c9dc23](https://github.com/fbprogmbh/Audit-Test-Automation/commit/6c9dc23b77f57073a435e9227d481121b4204fd5)
