### ISSUE TITLE
Error when creating Windows Server 2022 audit

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#159]
Error occurs when running Server 2022 Report. For more information, see screenshots.
![Error1part](https://user-images.githubusercontent.com/56861310/192753271-4ec4657e-2d46-4e44-bdc3-660f9d85d250.png)
![Error2part](https://user-images.githubusercontent.com/56861310/192753277-f7b053ce-a18c-4454-889d-9b10a6b66d3d.png)

**Comment by SteffenWinternheimer** [comment]
Fix Issue with commit [b14c2b4](https://github.com/fbprogmbh/Audit-Test-Automation/commit/b14c2b425dc708cc6457e10b4bf8dffc99f8b0c7)
