### ISSUE TITLE
Resolution of local administrator's group from Security Base Data Check fails on DC

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#160]
As DCs do not have local groups, this check fails.
Please make sure this check is set to not applicable for domain controllers.
![grafik](https://user-images.githubusercontent.com/68649859/197748947-49a9d2d7-4c32-4ddb-8204-0e7307e1cb9f.png)

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed.
