### ISSUE TITLE
Error Message when executing Windows 10 All report

### ISSUE THREAD

**Issue by unterzahl** [fbprogmbh/Audit-Test-Automation#162]
PS..Documents\ATAPReports> Save-ATAPHtmlReport -ReportName "Microsoft Windows 10 All"               Get-LocalGroupMember : Failed to compare two elements in the array.
At C:\Program Files\WindowsPowerShell\Modules\ATAPAuditor\AuditGroups\Microsoft Windows Security Base Data.ps1:486
char:20
+         $userAndGroups = Get-LocalGroupMember -SID "S-1-5-32-544"
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LocalGroupMember], InvalidOperationException
    + FullyQualifiedErrorId : An unspecified error occurred.,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand

Test-AuditGroup : Cannot convert null to type "AuditInfoStatus" due to enumeration values that are not valid. Specify
one of the following enumeration values and try again. The possible enumeration values are
"True,False,Warning,None,Error".
At C:\Program Files\WindowsPowerShell\Modules\ATAPAuditor\Reports\Microsoft Windows 10 All.ps1:20 char:19
+ ...   AuditInfos = Test-AuditGroup "Microsoft Windows Security Base Data"
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Test-AuditGroup

**Comment by qngngyn** [comment]
This error is known and fixed in upcoming release
Thanks for your feedback
