### ISSUE TITLE
Develop > Error when checking Bitlocker encryption status

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#163]
When running the report on a Windows 10 System with one drive and one BL encrypted Volume, this error occured. Please check:

![image](https://user-images.githubusercontent.com/68649859/201630350-5b29ef90-0efc-4417-b5d3-4a9b3238bb52.png)

![image](https://user-images.githubusercontent.com/68649859/201630554-90df5570-7158-4170-8fe6-483980d7b011.png)

**Comment by SteffenWinternheimer** [comment]
@TuemmlerKelch, can you please provide a screenshot of this test from your report?

**Comment by SteffenWinternheimer** [comment]
Fix Issue with commit [bd1fc50](https://github.com/fbprogmbh/Audit-Test-Automation/commit/bd1fc50abbf46dc8e8dba56804caeaf6ee4a6e12)

**Comment by qngngyn** [comment]
This error is still relevant. Interestingly only happens on execution of the report. On consecutive executions, it works without any Exception.
