### ISSUE TITLE
Improve Release and Build output

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#165]
Please try and align output of Build version towards output of "winver"
![image](https://user-images.githubusercontent.com/68649859/201638133-3d3665dc-1caf-4d45-af44-142e9afbe0ae.png)

This should be achievable by reading the values from registry and using the following piece of code to transform the output:

```
$v = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
# format output
'Version {0} (Build {1}.{2})' -f $v.DisplayVersion, $v.CurrentBuildNumber, $v.UBR
```

Rename **"Build Number"** to **"Version / Build"**

**Comment by TuemmlerKelch** [comment]
While you are at it, please also remove the (GB) from the headings and move those to the values
![image](https://user-images.githubusercontent.com/68649859/201640743-2182f5cb-5e9e-431b-b7db-18924eddd0ff.png)

**Comment by SteffenWinternheimer** [comment]
Enhancement added.
