### ISSUE TITLE
Non-existent accounts are declared orphaned accounts

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#167]
![image](https://user-images.githubusercontent.com/68649859/201643315-096e5317-b6e0-45e0-a6af-4fbddc446aa5.png)

The users "NT SERVICE\\ADFSSrv" and "NT SERVICE\\DRS services" do not exist on this system, as ADFS role is not installed.

Please account for this by checking if ADFS role is installed. If not, 2.2.30 A applies and B is not applicable.
If ADFS is installed, Those two accounts do exist and translation should work. Then 2.2.30 A is not applicable.

This applies to all existing Server Benchmarks.

**Comment by SteffenWinternheimer** [comment]
Further testing required now.

**Comment by SteffenWinternheimer** [comment]
Testing successfully done with Windows Server 2022. Issue will be closed for now.
