### ISSUE TITLE
Add system uptime to "foundation data" of system 

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#169]
Please add system uptime to foundation data in order to check how long a system is running already - if running half year might be cool from tech point of view but also indicates it is not patched since months...

Under PoSH 7.x this should work: 
`get-uptime `

Under PoSh 5.x this should work:
`(get-date) - (gcim Win32_OperatingSystem).LastBootUpTime`

Please test with Linux.

**Comment by SteffenWinternheimer** [comment]
Enhancement added.
![grafik](https://user-images.githubusercontent.com/35689334/202196562-7852dcbb-8eb4-40f5-be4b-cf516ce0f299.png)
