### ISSUE TITLE
[Sql2016Benchmarks] Importing SQL module failed

### ISSUE THREAD

**Issue by devesly** [fbprogmbh/Audit-Test-Automation#17]
SQL Server is hardend, user is admin on windows machine and sql server.

![image](https://user-images.githubusercontent.com/25382803/55234942-8bdbfe80-522c-11e9-919c-11060d6ba077.png)

**Comment by flobroeder** [comment]
Dear Dennis, we have had a look into your issue, it is fixed in our new version 4 which is going to be published this evening. Kind regards!
