### ISSUE TITLE
Windows Server 2022 Report includes MS DC Benchmark

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#170]
please make sure to follow the current pattern and exclude the DC Benchmark from Server 2022 "standard" report.
If necessary also create a 2022 DC Benchmark.

**Comment by SteffenWinternheimer** [comment]
Windows Server 2022 Report has been split into "Standard" and "Domain Controller". Further testing required.

**Comment by SteffenWinternheimer** [comment]
Reports have been tested ("Standard" and "Domain Controller"). Issue will be closed now.
