### ISSUE TITLE
SBD-40 should also apply to Windows 11 Enterprise

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#173]
please also implement for Windows 11.

Question towards functionality:
Is this based to identify if the device is capable of using WDAC, or if it is actually configured to do so?
Currently, the check would only indicate the first.

**Comment by SteffenWinternheimer** [comment]
Add check also to Windows 11 Enterprise. Currently it is based on the check if OS-Name is "Windows 10/11 Enterprise" or not.
