### ISSUE TITLE
Windows 11 benchmark does not reflect table from readme.md

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#174]
According to readme: 
![image](https://user-images.githubusercontent.com/68649859/205310590-c696c8f5-4ef5-463e-a52f-f8d77565c7d9.png)

actual implementation: 
![image](https://user-images.githubusercontent.com/68649859/205310639-208c5b92-3fcc-42c5-9de8-8a6d068eb23e.png)

Suggestion:

- Remove RTLF
- Include MS Windows 11
- BSI SiM-08202 Client unter Windows 10, Version: 1, Date: 2017-09-13
- Configuration Recommendations for Hardening of Windows 10 Using Built-in Functionalities: Version 1.3, Date: 2021-0

The last two, BSI-guidelines are designed for Windows 10, but apply to Windows 11, too.

This would in my opinion justify to push extend timeline for Release 5.3

**Comment by SteffenWinternheimer** [comment]
![grafik](https://user-images.githubusercontent.com/35689334/206147504-258c83fa-0191-45c1-888f-32e49180dc34.png)

Issue fixed. Windows 11 now includes BSI AuditGroups for a better comparison between Windows 10 and Windows 11

**Comment by TuemmlerKelch** [comment]
@SteffenWinternheimer Please check whether Windows 11 Benchmark really is 20H2 or 21H2. I expect it's the latter.

**Comment by qngngyn** [comment]
The above fix is originally issued for #175.
