### ISSUE TITLE
Client OS Benchmarks > BSI > select HD, ND or NE Benchmark based on domain role

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#175]
**Successor to Issue #174.**

Currently, we carry out both HD, ND and NE test regardless of domain role.

Please implement it in a way that we carry out the following:

**Standalone Workstation**
- NE

**Member Workstation**
- ND
- HD

As of now, this would only affect Windows 10 Benchmark.

Please close this issue once this is implemented for both Windows 10 **and** Windows 11.

**Comment by SteffenWinternheimer** [comment]
That would mean, we would have to make separate Reports for this case, something like "Microsoft Windows 10 Standalone Workstation" and "Microsoft Windows 10 Member Workstation". Let's discuss about this ticket again.

**Comment by qngngyn** [comment]
A fix has been implemented with [a587e99](https://github.com/fbprogmbh/Audit-Test-Automation/commit/a587e99aa34aaed6128a753ff3ccddb2d07de720). Pull request has been requested.

**Comment by SteffenWinternheimer** [comment]
Pull request has been approved and merged together.
