### ISSUE TITLE
Header not correct

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#18]
<img width="404" alt="scr_header_audit_report" src="https://user-images.githubusercontent.com/23223285/55418253-91aa4a80-5572-11e9-9ba3-b544cf37ca40.PNG">

* Should be Mozilla Firefox
* Should be DISA and CIS...

**Comment by Beneboe** [comment]
Fixed in c01e9d7cb098fad831c840c0cbba3838e36a6455
