### ISSUE TITLE
Change calculation to not regard settings that do not apply

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#181]
Currently, calculation is also including settings that are not applicable. Example

Target is Member server

total checks: 15
true: 7
false: 3
warn: 0
not applicable: 5

Conformity should be 70% here (true/(total checks - not applicable))
however, it is only 46% with current logic

**Comment by SteffenWinternheimer** [comment]
Issue has been Fixed. Now the risk score calculation will be calculated by excluding all "None"-Compliant and then get the percentage of Quantity compliance from the total amount of tests.
