### ISSUE TITLE
Please enrich help content and write professional help with a few more examples

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#186]
This screnshot looks a bit empty...

![image](https://user-images.githubusercontent.com/23223285/207959630-022c7f9d-3f53-4792-9e64-af741687c905.png)

Please use this as a guideline: 

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.3

**Comment by SteffenWinternheimer** [comment]
Update description of function Save-ATAPHtmlReport
