### ISSUE TITLE
Compliance is better than requested - although "non compliant"

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#188]
On my machine no one has "SeDebugPrivilege"...
Although we are better than requested we get a "non compliant"...

Let us discuss this...

![image](https://user-images.githubusercontent.com/23223285/207962191-3707b78b-5abc-47de-904f-f1c977a36b5f.png)

**Comment by flobroeder** [comment]
Same here...

![image](https://user-images.githubusercontent.com/23223285/207962787-0bf80c58-bb89-48f8-8c50-6afa0042906b.png)

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed. Now the tests print proper compliant status.
