### ISSUE TITLE
Is a split missing here? 

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#189]
Is the only option "hyper-V not installed" or is a split missing here? 

![image](https://user-images.githubusercontent.com/23223285/207962399-aa2a7d0f-6a83-45ab-a36c-00578d29c115.png)

**Comment by SteffenWinternheimer** [comment]
Two options are possible: [Hyper-V-Feature installed] or [Hyper-V-Feature NOT installed]
In this case the logic test was wrong. It has been fixed now and should internally change between both, depending on installation of Hyper-V
