### ISSUE TITLE
Rules seem to lead to different compliance results in same report

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#190]
Non Compliance here: 

![image](https://user-images.githubusercontent.com/23223285/207963150-bee227b1-ba8c-4217-912c-1d3d4a7eb014.png)

For accpunt lockout there is compliance? 
![image](https://user-images.githubusercontent.com/23223285/207963539-348462ae-2428-4683-adde-e8107c7181ef.png)

Is this another rule or a bug?

**Comment by SteffenWinternheimer** [comment]
After research, these rules are different from each other. CIS locks the account, while BSI locks the whole PC via TPM.
