### ISSUE TITLE
Validation rule wrong?

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#192]
This is what AuditTAP report shows: 

![image](https://user-images.githubusercontent.com/23223285/207964817-8d48d581-fe52-4573-a5b3-10b9d03cfdb1.png)

This is what reality is:

![image](https://user-images.githubusercontent.com/23223285/207965883-decf0223-dcd4-4d97-a55f-6bb5bdbf8e5c.png)

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed. Now these Rules are tested by this cmdlet.
