### ISSUE TITLE
Check Bitlocker logic

### ISSUE THREAD

**Issue by SteffenWinternheimer** [fbprogmbh/Audit-Test-Automation#200]
Check logic of SBD-012 test (where bitlocker encryption is checked). Looks like if all volumes are fully encrypted, result shows an 'error'.

**Comment by qngngyn** [comment]
#163
This is a known issue and is something that is out of our scope. Workaround is rerunning the ATAP: Error only occurs on first run of ATAP. There is no fix inside, because the exception is thrown internally.
