### ISSUE TITLE
[PR2] Error for systems with uninstalled defender

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#218]
On systems without Windows Defender, the command Get-MpComputerStatus runs into an error.

You can easily check if Defender is installed with the following command
(get-WindowsFeature -Name Windows-Defender).installed

![image](https://user-images.githubusercontent.com/68649859/214034901-21334d3f-684f-45bd-b5b4-6357001cafc3.png)

**Comment by qngngyn** [comment]
Alternatively "Get-Service -Name WinDefend" works as well. It might be better than "(get-WindowsFeature -Name Windows-Defender).installed" since the second one does not work on Windows client-based operating systems. This is to check on a server as well.

**Comment by qngngyn** [comment]
Fixed with https://github.com/fbprogmbh/Audit-Test-Automation/commit/f4558086f51c4dc8d7ed5ad2ed5c3aeb0cdbdfd0
