### ISSUE TITLE
Error after updating to version 5.3

### ISSUE THREAD

**Issue by iTdee** [fbprogmbh/Audit-Test-Automation#219]
PS C:\WINDOWS\system32> Save-ATAPHtmlReport -ReportName "Microsoft Windows 10"
Get-ATAPHtmlReport : Es wurde kein Parameter gefunden, der dem Parameternamen "RiskScore" entspricht.
In C:\Program Files\WindowsPowerShell\Modules\ATAPAuditor\5.3\ATAPAuditor.psm1:547 Zeichen:77
+ ... Name $ReportName | Get-ATAPHtmlReport -Path $Path -RiskScore:$RiskSco ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ATAPHtmlReport], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-ATAPHtmlReport

**Comment by qngngyn** [comment]
Hello! 
Please make sure to also update your ATAPHtmlReport Module, not only your ATAPAuditor. If you've done so, make sure to "Import-Module ATAPHtmlReport" beforehand. Chances are, that your ATAPHtmlReport Module is still the old one that requires the "RiskScore"-Parameter.

**Comment by SteffenWinternheimer** [comment]
Hey there!
I can confirm that using the latest version (5.3.) provides the RiskScore. I tried the AuditTAP on a fresh system with the latest version and the RiskScore is working without any issues.

**Comment by iTdee** [comment]
Thnx for you help! Perhaps the update process should be documented a little more precisely.

**Comment by TuemmlerKelch** [comment]
> Thnx for you help! Perhaps the update process should be documented a little more precisely.

Good idea. Opened #224
