### ISSUE TITLE
[PR2] Windows Defender is disabled, other tool is used - although it is marked as "green"

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#225]
See screenshot below...that seems to be weird...

![image](https://user-images.githubusercontent.com/23223285/215050182-5e23dc0f-927f-44fc-b09b-6b4dd20b433d.png)

**Comment by SteffenWinternheimer** [comment]
For a better logic check, validation has been changed from checking corresponding registry key to following cmdlet: 
(Get-MpComputerStatus).RealTimeProtectionEnabled
Waiting for response of pull request for this ticket.
