### ISSUE TITLE
DISA Server 2022 Benchmark optimization

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#234]
DC only -> please adjust:
V-254416
V-254417

"V-254319 + V-254320" needs fixing
![image](https://user-images.githubusercontent.com/68649859/216693379-d9c48d32-07aa-40ce-b3e8-316018369a97.png)

**Comment by TuemmlerKelch** [comment]
@SteffenWinternheimer Let's actually split those Logging controls into 2 parts rather than keeping them combined.
This way it is more transparent if one of the two checks fails.

**Comment by SteffenWinternheimer** [comment]
Splitting these controls won't work due to the reason that every check can be only done once in our tests. Splitting both controls when they check for the same setting would be a duplicate check here.

**Comment by SteffenWinternheimer** [comment]
Issue appears in multiple auditgroups. Ticket will be pushed back for a later release (Release 5.5).
