### ISSUE TITLE
"DarkMode" looks weird in case "riskscore" parameter is used...

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#236]
See screenshot below...

![image](https://user-images.githubusercontent.com/23223285/216815425-9e5c6e45-3d94-4e8b-bf20-f5e0457688e9.png)

**Comment by SteffenWinternheimer** [comment]
Optimization of the "DarkMode" will be done at a later time. Disabling DarkMode Switch for now.

**Comment by TuemmlerKelch** [comment]
Decision: We will get rid of dark mode and all related code.

**Comment by SteffenWinternheimer** [comment]
Pull request merged. Issue will be closed now
