### ISSUE TITLE
[PR 3] Check for DomainController has obviously wrong check/logic

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#237]
Tested on normal Windows 10"

![image](https://user-images.githubusercontent.com/23223285/216815485-b40e4e41-28e8-46cf-8ce8-94d30a7e1cc7.png)

**Comment by SteffenWinternheimer** [comment]
This rule had a constraint that it only worked on DC systems. I removed the constrains on this test and now its printing out the correct amount of admins. Waiting for approval.
