### ISSUE TITLE
[PR 3] Wrong logic for "Debug programs" privilege

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#238]
In case "Debug programs" (SeDebugPrivilege) is not assigned to anyone it makes a configuration more secure...
So this logic should be implemented here.

So this setting is "compliant" if it is only "Administrator" or no one...

![image](https://user-images.githubusercontent.com/23223285/216815557-2c8f2d13-9cd6-4024-aff6-789a3a2b5550.png)

Please also check all additional audits for this settings from other hardening recommendations...

**Comment by SteffenWinternheimer** [comment]
Fix logic along with appearence in other auditgroups. Waiting for approval #244
