### ISSUE TITLE
Problem saving the report

### ISSUE THREAD

**Issue by andrelindenfb** [fbprogmbh/Audit-Test-Automation#239]
If the path is changed as in the example:

Save-ATAPHtmlReport -ReportName "Microsoft Windows 10 Complete" -RiskScore -Path C:\Temp\report.html

it will not be created. Unfortunately, there is also no indication that the path does not exist. The report is then saved in the default folder, but here only as ATAPReports and not in the desired file format.

**Comment by flobroeder** [comment]
Please add system version (Windows 10, 11, Server?), screenshot and step by step guide so that developers are able to reproduce the issue...
