### ISSUE TITLE
[PR 3] Section naming seems to be wrong

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#241]
Tested on Windows Server 2019 - sure it is both "Audit Policy configuration"? 

![image](https://user-images.githubusercontent.com/23223285/216953952-65168be4-68d4-4be4-8994-54a95e688a1f.png)

**Comment by SteffenWinternheimer** [comment]
typo has been fixed, waiting for approval in pull request
