### ISSUE TITLE
[PR 3] TPM status should not be error in case TPM is available but not used...

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#242]
Tested on virtual machine Server 2019, TPM available but not used...
Should be "non compliant"...

![image](https://user-images.githubusercontent.com/23223285/216954482-a865ca95-df59-4d71-a858-a7d9e25a8625.png)

**Comment by SteffenWinternheimer** [comment]
Obviously it seems like the cmdlet Get-TPM has less information when running on Windows Server.... Changing this cmdlet to wmi checks resolves this problem.
Based on this article: https://techdirectarchive.com/2022/02/03/how-to-determine-if-tpm-is-present-and-how-to-enable-tpm-in-the-bios-via-the-command-prompt/
