### ISSUE TITLE
[Windows10Audit] Problems with non-english OS

### ISSUE THREAD

**Issue by Beneboe** [fbprogmbh/Audit-Test-Automation#25]
User Rights Assignment causes problems, because it uses `ConvertTo-NtAccount` function. The `ConvertTo-NTAccount` function cannot translate english account names to SIDs.

**Comment by flobroeder** [comment]
Will not be fixed. Audit TAP runs perfect on english base os images with installed language packs. So please install "english" operating system,  than apply language pack for globalization/localization.

**Comment by flobroeder** [comment]
Is corrected and implemented in release 4.3
