### ISSUE TITLE
In new standalone reports (Windows 10 / Windows 11) firewall logging for domain profile is checked

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#267]
See screenshot: 

![image](https://user-images.githubusercontent.com/23223285/220966536-b80f89fd-049d-4293-9bf3-3375b49598b2.png)

Expectation is that "domain firewall" test is skipped, so please add a check here if system is standalone and in case "yes" provide "none".

**Comment by TuemmlerKelch** [comment]
These checks need to be added to the BSI Logging audit groups for the following 4 IDs:
4.2.1.1
4.2.1.2
4.2.1.3
4.2.1.4
