### ISSUE TITLE
[WindowsServer2016Audit]: module import warning 

### ISSUE THREAD

**Issue by devesly** [fbprogmbh/Audit-Test-Automation#27]
![image](https://user-images.githubusercontent.com/25382803/58023294-c157e680-7b0f-11e9-992e-a6df204e63d5.png)

**Comment by flobroeder** [comment]
Dear Dennis, we have had a look into your issue, it is fixed in our new version 4 which is going to be released this evening. Importing individual modules for reports is no longer required - please refer to updated "readme" for further details. Kind regards!
