### ISSUE TITLE
MS Security Baseline Privileges are unclear

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#288]
Is text correct? 

![image](https://user-images.githubusercontent.com/23223285/224476120-445d6f45-229a-4a7b-9ab5-2cb159c04c46.png)

**Comment by qngngyn** [comment]
I have checked, and seems to be correct (checked in Benchmarks)
please close the thread, when this answer satisfies the question.

**Comment by SteffenWinternheimer** [comment]
For now we keep the text. 
[...] is set to "" means that this privilege is set to 'No one'. 
We will update the text quality in the future.

**Comment by TuemmlerKelch** [comment]
Please change all instances _**of is set to ''**_ into _**of is set to 'No One'**_ 
This way it is both clear and aligned to CIS-format.
