### ISSUE TITLE
It is currently necessary to use a subfolder

### ISSUE THREAD

**Issue by PeterUIXIV** [fbprogmbh/Audit-Test-Automation#29]
It is currently necessary to use a subfolder in order to create a html-report.
![grafik](https://user-images.githubusercontent.com/40171686/58976718-6f2deb00-87c8-11e9-8a2c-1d716ad0baeb.png)

This Problem does not exist for Windows 10 Report.

**Comment by flobroeder** [comment]
Dear Peter, thank you. We have had a look into your issue, it is fixed in our new version 4 which is going to be published this evening. Please check the also updated "readme" for further details. Kind regards!
