### ISSUE TITLE
Checking service state for DiagTrack Service seems to be wrong in BSI benchmark

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#290]
**Service is disabled on system**

![image](https://user-images.githubusercontent.com/23223285/224476424-e222c6fd-babd-47d3-9fb6-5bb95949980c.png)

**AuditREport shows "false"**
![image](https://user-images.githubusercontent.com/23223285/224476408-0c96be0d-0670-412e-ab48-51efb3e7c8a1.png)

**Comment by SteffenWinternheimer** [comment]
Logic check has been updated to check now the status via PowerShell cmdlet:
Get-Service DiagTrack | select -property starttype
