### ISSUE TITLE
License status is not detected or displayed on Server 2019 member server

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#292]
![image](https://user-images.githubusercontent.com/23223285/224477107-7b847222-e895-43d9-9430-c4c1c3b3d7dc.png)

**Comment by qngngyn** [comment]
Can this be investigated on the server at question by inserting into the powershell the following check: 
(Get-CimInstance SoftwareLicensingProduct -Filter "Name like 'Windows%'" | where { $_.PartialProductKey } | select Description, LicenseStatus -ExpandProperty LicenseStatus)

And seeing the result... 
Guesses are that the checks work on both sides the same, but nothing is returned from the license check. Therefore running into said outcome.

Tests with the license checks on my 2019 servers work, so we need to investigate this further.

**Comment by flobroeder** [comment]
It is a Windows Server 2019 test system, unlicensed, return value is “5” according to the license status…
See screenshot below:

![image](https://user-images.githubusercontent.com/23223285/224532439-66c50fea-3919-4a7e-ace3-313cc6d5fd48.png)

**Comment by SteffenWinternheimer** [comment]
License logic check has been updated and a pull request has been created for this ticket (#295). The old check seemed to only return a value, if the system is licensed, with the new check, it returns a value for each status of license. Waiting for approval.
