### ISSUE TITLE
AppCompat check is wrong - it is disabled but "non compliant"

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#304]
AppCompat should be disabled - it is.
Please adopt check and enrich logic rule for also checking if it is completely disabled:

Machine reality: 
![image](https://user-images.githubusercontent.com/23223285/224755397-4e177bd6-4de5-4401-ac2e-62713ef10469.png)

AuditTAP status:
![image](https://user-images.githubusercontent.com/23223285/224755294-5d6db758-852f-42ea-b70d-65e3e6f93e0d.png)

**Comment by SteffenWinternheimer** [comment]
It seems like the rule does what it should do. The rule checks for the following registry key:
![grafik](https://user-images.githubusercontent.com/35689334/225253985-98b5caac-4eea-4953-8ad5-b51818bc5dcf.png)
DISA also refers to the valueName "DisableInventory":
https://www.stigviewer.com/stig/microsoft_windows_server_2012_member_server/2013-07-25/finding/WN12-CC-000071
![grafik](https://user-images.githubusercontent.com/35689334/225254291-a303339e-3ca3-46de-9e97-b94f7af005ea.png)

And on the admx.help i have found this entry as well:
https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.ApplicationCompatibility::AppCompatTurnOffProgramInventory
![grafik](https://user-images.githubusercontent.com/35689334/225254546-947b8159-26bd-44db-8a04-1624de108a1a.png)

**Comment by flobroeder** [comment]
All correct, but: 
The statement here is more that this setting is no longer relevant if the underlying service is completely disabled. It is the same as configuring ASR rules when Windows Defender is disabled. They are not effectiv.

So in case the AppCompat Service is disabled (which it is in the test case) the configuration of the "inventory collector" is irrelevant as the service is disabled.

See: https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.ApplicationCompatibility::AppCompatTurnOffProgramCompatibilityAssistant_2

_Quote: The Diagnostic Policy Service (DPS) and Program Compatibility Assistant Service must be running for the PCA to run._

In our case the "Program Compatibility Assistant Service" is stopped and disabled...
