### ISSUE TITLE
IIS Audit needs to check SCHANNEL registry values for alternate Enabled value of 0xffffffff

### ISSUE THREAD

**Issue by isaacg123** [fbprogmbh/Audit-Test-Automation#31]
After using IIS Crypto: https://www.nartac.com/Products/IISCrypto/ I tried running IIS10Audit again and was still getting failures. After digging further I noticed they were changing the values to 0xffffffff as enabled instead of dword 1. So I emailed them and they confirmed that is intentional behavior:

> Actually both are valid. Microsoft's own documentation also conflicts with itself:
> https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc
> IIS Crypto originally set them to 1 and then a bunch of people complained as it did break software (not audit tools) so we changed it to the proper 0xffffffff. IIS Crypto will read both 1 and 0xffffffff when run though.

So I would request that IISAudit check for both values as valid Enabled.

**Comment by flobroeder** [comment]
Dear isaacg123, we have had a look into your issue, it is fixed in our new version 4 coming soon - hopefully this evening ;-) Please also check new version of IIS Crypto 3.2. Kind regards!

**Comment by flobroeder** [comment]
Check it out here: https://github.com/fbprogmbh/Audit-Test-Automation/releases/tag/v4.0

**Comment by SergGu** [comment]
Please update "Microsoft IIS10.ps1" The 7.11 check is still looking for 1 rather then 0xffffffff 

Looks like both are fine, but most of the tools are checking for a later option
Also found those explanations online:
- Technically speaking, any non-zero value would match to "Enabled".
- Unsigned 0xffffffff (hex) = -1 (decimal so it really isn't different, end result is "enabled"

Code, as it stands today:
```
# 7.11
function Test-IISAES256Enabled {
	<#
	.Synopsis
		Ensure AES 256/256 Cipher Suite is enabled
	.Description
		AES 256/256 is the most recent and mature cipher suite for protecting the confidentiality and integrity of HTTP traffic. Enabling AES 256/256 is recommended. This is enabled by default on Server 2012 and 2012 R2.
	#>

	$message = "AES 256/256 Cipher is disabled"
	$audit = "False"

	$path = "HKLM:\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256\"

	if (Test-Path $path) {
		$Key = Get-Item $path
		if ($null -ne $Key.GetValue("Enabled", $null)) {
			$value = Get-ItemProperty $path | Select-Object -ExpandProperty "Enabled"
			if ($value -eq 1) {
				$message = $MESSAGE_ALLGOOD
				$audit = "True"
			}
		}
	}
```
