### ISSUE TITLE
DC Audit states Not applicable in the report.

### ISSUE THREAD

**Issue by andrelindenfb** [fbprogmbh/Audit-Test-Automation#310]
A "Microsoft Windows Server 2022 DC" audit was performed on the following system.

![Info_2022_DC](https://user-images.githubusercontent.com/47269097/225247931-7490fbe2-3c55-46af-8a58-c2552758f293.jpg)

In the audit, this review takes place.

![Result_2022_DC](https://user-images.githubusercontent.com/47269097/225247970-f928f3c9-8f94-4499-96c7-0b9f36689482.jpg)

**Comment by qngngyn** [comment]
Errormessage was wrong. Tests have shown that for domain controllers, there must be manual check for this audit test.
The output will be a better errormessage, but change to an error.
