### ISSUE TITLE
Check following CIS Splits for Windows Server 2016

### ISSUE THREAD

**Issue by SteffenWinternheimer** [fbprogmbh/Audit-Test-Automation#322]
The following screenshots provided show that at least one of the test will always result in "false". Please update logic check here.
![grafik](https://user-images.githubusercontent.com/35689334/230025850-1f09653e-6b9a-4fb0-8546-196ba8b9f1f8.png)
![grafik](https://user-images.githubusercontent.com/35689334/230026023-1263c042-7040-48d8-9002-dd3b5dbf2e86.png)

**Comment by TuemmlerKelch** [comment]
This also needs to be solved for all other server audit groups
