### ISSUE TITLE
Add missing TLS Checks for TLS 1.2

### ISSUE THREAD

**Issue by SteffenWinternheimer** [fbprogmbh/Audit-Test-Automation#326]
Currently we only have a check for TLS 1.2 for Server:
![grafik](https://user-images.githubusercontent.com/35689334/234003418-815ad546-fb08-410d-ac27-bacaff47b5f4.png)

We also should check for TLS 1.2 on Client systems as well.

Default if TLS 1.2 registry path doesn't exist on Windows 11 and Windows Server 2022, it would be still compliant, if the path is null, keep that in mind because these tests would also be tested on older systems (e.g. Windows 7 etc.) due that these tests appear in SecurityBaseData

HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
DisabledByDefault = 0
Enabled = 1

Add to SBD. I will discuss if we will also add this to FB Pro Checks and Benchmark

**Comment by TuemmlerKelch** [comment]
Please refer to this article for compatibilities and registry paths

**Comment by TuemmlerKelch** [comment]
Merged Pull request, but only solved half of this issue. Please add this to Security Base Data and make sure it has the correct order. 
![image](https://github.com/fbprogmbh/Audit-Test-Automation/assets/68649859/0411daab-7df3-4edd-adec-60af356d5d7a)
