### ISSUE TITLE
Generate report using ATAPHtmlReport

### ISSUE THREAD

**Issue by avi8892** [fbprogmbh/Audit-Test-Automation#33]
In a case there is no option to install PS version 5/5.1, how can I still generate a report ?
Can you explain me on how to run all the task manually without report, using the functions (such as Full site report) ?

**Comment by flobroeder** [comment]
Dear AviOz, Powershell 5 is a requirement to run the report. At this point of time we cannot support other version with this free to use Audit TAP. Kind regards
