### ISSUE TITLE
Include latest CIS/MSFT benchmarks for Windows 11 22H2?

### ISSUE THREAD

**Issue by c3rberus** [fbprogmbh/Audit-Test-Automation#330]
Hello,

This is a great utility that will make life easier securing Windows domain.

Are there any plans to add support for CIS Microsoft Windows 11 Benchmark v2 (_based on Microsoft Windows 11 Enterprise Release 22H2_) and Microsoft's Windows 11, version 22H2 Security baseline?

**Comment by TuemmlerKelch** [comment]
Hey c3rberus, thanks for reaching out to us. We will be adding both of those in the future, starting with CIS, then MS baseline.
Release 5.6 will definitely be featuring CIS v2 Benchmarks for Windows 10/11 and possibly already some of the server benchmarks.

**Comment by TuemmlerKelch** [comment]
@c3rberus MS Windows 11 Baseline 22H2 will be worked on with #361
