### ISSUE TITLE
Risk score is always either critical or low. what condition it will show Medium and High?

### ISSUE THREAD

**Issue by satyendra22** [fbprogmbh/Audit-Test-Automation#331]
@SteffenWinternheimer 
Thanks for the risk calculation matrix. I'm little confused about the risk calculator. Its seems it always risk score is either critical or low.
It never Medium and High due to the Severity Risk assessment. Can you explain when it will Medium or High Risk score ?

**Comment by SteffenWinternheimer** [comment]
Thank you very much for using our AuditTAP! 

We currently have a selected set of rules which are related to the Severity calculation of the risk score. These rules are listed right under the risk score matrix in the tab "Risk Score". All of these rules have the severity "Critical", which leads to a critical calculation if at least one of these rules is not compliant. 
In the near future we want to assign an individual severity for each tested rule on the system to reach a more precise calculation regarding to the severity, depending on the rule that could be "Medium" or "High".

I hope I could help you out. If there is still something unclear, feel free to reach out to me again!

**Comment by satyendra22** [comment]
Thanks for prompt response.  If i want to select some tasks as High not all critical, do we have any option do that and calculate the risk accordingly?

**Comment by SteffenWinternheimer** [comment]
Sorry for late response. Now to your question:

That would require some major tweaks in the code. 
The process would be something like this: 
- Setting a severity tag on corresponding AuditTests (Low/Medium/High/Critical); would be done inside the AuditTests as well as updating class "AuditTest" in ATAPAuditor.psm1 by a new variable
- Update function Test-AuditGroup (ATAPAuditor.psm1) to collect severity of tests and check for the most severe outcome
- Pipe the results to ATAPHtmlReport.psm1 so the results will be displayed on the report itself.

As mentioned before, we will implement this feature in the near future, not sure when, but you can of course fork the repository and make changes there by yourself!

Greetings,
Steffen
