### ISSUE TITLE
Include a comparison of the reportname with OS / Role followed by a question

### ISSUE THREAD

**Issue by svndh** [fbprogmbh/Audit-Test-Automation#336]
### **Issue:**

The User chooses for example to create an AuditTAP report based on the Reportname _Microsoft Windows Server 2019_.

From now on, all of the following scenarios are possible:

1. The User does know that the underlying OS is _Microsoft Windows Server 2019_ and therefore he chose the right reportname.
2. The User **thinks** that the underlying OS is _Microsoft Windows Server 2019_ but actually it is _Microsoft Windows Server 2016_ and he still chose the Reportname _Microsoft Windows Server 2019_. --> User has made a mistake and the results are affected
3. The User does know that the underlying OS is _Microsoft Windows Server 2016_ and for some purpose the user still chose the reportname of another role --> User made a conscious choice

### **Solution**

1. Perform a comparison of the report name with the operating system / role from which the report creation is started.
2. If reportname and OS/Role differ, generate a prompt for the user with a short description
3. Also include a comparison of role differences (for example OS is _Microsoft Windows Server 2019 with installed DC Role_ but user only chooses _Microsoft Windows Server 2019_ and **vice versa**)
4. If reportname and OS/Role do **not** differ, everything works as usual

Question could be implemented like the **both** following examples:

### Example only with OS

**Reportname Validation**
You chose the Reportname __Microsoft Windows Server 2019_ but the operating system is __Microsoft Windows Server 2016_. 
Be aware that a different report type could affect the result. Do you really want to continue? 
[Y] Yes [N] No

### Example with OS and Role

**Reportname Validation**
You chose the Reportname __Microsoft Windows Server 2019_ but the operating system is __Microsoft Windows Server 2019 acting as a Domain Controller_. 
Be aware that a different report type could affect the result. Do you really want to continue? 
[Y] Yes [N] No

**Comment by TuemmlerKelch** [comment]
Great idea. I suggest implementing it like this:
We concentrate **only** on OS and type (standalone or domain member). Should desired report not match actual report, we present the user with the following:

Selected report ($reportname) and actual OS ($actualOS) do not match. Please select one of the following options:
1 - Create report for ($actualOS)
2 - Continue with your selection ($reportname)
3 - Show available reports

**Comment by TuemmlerKelch** [comment]
Not implemented for Linux, but fine for Windows
