### ISSUE TITLE
Visual redesign report sections and header

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#350]
Please see the screenshots I delivered to you already

Redesign Header

- Move Company to top right and add logo
- Add Title and Versions to top left
- Move Report details from below section

Body 

- Benchmark Compliance
  - Remove unnecessary information
  - Move Details up

- Security Base Data
  - Rework text passages
  - Add delimiter to System Information

- Risk Score
  - Rework different text passages
  - Add "Risk Score Details" Header to Rules section

- Hardening Settings
  - Rework Overall integrity text

**Comment by SteffenWinternheimer** [comment]
Header has been updated. 
Benchmark Compliance has been updated.

**Comment by TuemmlerKelch** [comment]
Solved with PullRequest #437
