### ISSUE TITLE
5.2 Ensure Advanced IIS logging is enabled

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#37]
Advanced IIS logging is not used since IIS 8.5-
However CIS IIS shows with this point, that enhanced IIS logging is the tool now and that companies should be aware of this point.
Advanced Logging is not available for IIS 10. See enhanced logging instead. maybe this should be changed, showing where to find Information about Enhanced logging.

**Comment by PatHelb** [comment]
works as designed
