### ISSUE TITLE
Update all MS Windows Baselines to follow the proper logic

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#372]
Exclude IE settings and make sure MS and DC settings are not used both

Status:
|Baseline|Status|
|-|-|
|Windows 10|Open|
|Windows 11|Open|
|Server 2016|Open|
|Server 2019|Open|
|Server 2022|Open|

**Comment by SteffenWinternheimer** [comment]
IE settings do not only apply to IE but are deeply integrated into system behavior, thus we' will keep it.
Regarding MS and DC behavior, there was nothing to change. As a result we will scrap this issue.
