### ISSUE TITLE
revise check for (BL) Ensure 'Allow access to BitLocker-protected fixed data drives from earlier versions of Windows' is set to 'Disabled'

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#389]
This check seems odd
![image](https://github.com/fbprogmbh/Audit-Test-Automation/assets/68649859/fb4ad954-127e-45f0-8d39-e0aab7483e70)

**Comment by qngngyn** [comment]
Key in question and a few others are returned to have <none>, which will oddly lead to above behaviour.

To be done:
- find all keys that have <none>
- accept <none> as "" (or NULL, or EMPTY)
