### ISSUE TITLE
IIS10 Test 3.10 Future versions stopped supporting this feature

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#39]
This only applies to .Net 2.0. Future versions have stopped supporting this feature.
Future versions may have stopped supporting this feature, however if this is hardened, then the application just stop working.
Maybe a warning would be enough for checking this point.

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/ef4d804f578306132bf941488487313dcbeb8780
