### ISSUE TITLE
Improve SMB Server Signing check for incoming change in MS logic behavior

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#397]
MS will change behavior in current builds and we need to adapt our logic in advance to be able to cover systems using either the new or the old way. See below article for details.

Excerpt.
Any auditing tools that look at the registry could give false information. Use [Get-SmbServerConfiguration](https://learn.microsoft.com/powershell/module/smbshare/get-smbserverconfiguration?view=windowsserver2022-ps) and [Get-SmbClientConfiguration](https://learn.microsoft.com/powershell/module/smbshare/get-smbclientconfiguration?view=windowsserver2022-ps) or the CIM classes [MSFT_SmbClientConfiguration](https://learn.microsoft.com/previous-versions/windows/desktop/smb/msft-smbclientconfiguration)and [MSFT_SmbServerConfiguration](https://learn.microsoft.com/previous-versions/windows/desktop/smb/msft-smbserverconfiguration) and ensure any scripts or auditing tools use them (this has been the right approach for all SMB settings for a decade).

https://techcommunity.microsoft.com/t5/storage-at-microsoft/smb-signing-required-by-default-in-windows-insider/ba-p/3831704

**Comment by SteffenWinternheimer** [comment]
Luckily its explained pretty easy. The following RegistryKeys have to be exchanged with the corresponding cmdlets and their fields
![grafik](https://github.com/fbprogmbh/Audit-Test-Automation/assets/35689334/fbb66ad2-a42e-44a7-850b-d6fe41238aaf)
![grafik](https://github.com/fbprogmbh/Audit-Test-Automation/assets/35689334/3dfcb226-a939-44e6-a18b-f2f8260c6f64)
