### ISSUE TITLE
IIS10 Cannot read the configuration file

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#40]
Please check: if an application is not available, because of not existing physical folder. Audit TAP should mark them, and should not try to read the web.config.

Error message:
Ausnahme beim Aufrufen von "GetSection" mit 1 Argument(en):  "Dateiname: \\?\C:\Program Files 
(x86)\Plesk\admin\services\public\web.config
Fehler: Die Konfigurationsdatei kann nicht gelesen werden

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/ef4d804f578306132bf941488487313dcbeb8780
