### ISSUE TITLE
Problem to generate report with Win server 2022 with Windows IIS 10 script

### ISSUE THREAD

**Issue by RackAmpS** [fbprogmbh/Audit-Test-Automation#402]
Dear,

i got an issue when trying the run the cmd on Win server 2022 for "Microsoft IIS10"  : 
PS C:\Windows\system32> Save-ATAPHtmlReport -ReportName "Microsoft IIS10" -RiskScore -Path C:\Temp\report.html

Folder exist, and the same cmd work on Win Server 2019, and also if i try the report with the "Microsoft Windows Server 2022" on the Win server 2022 / 2019 this one work.

Here's the error i got : 

Get-ATAPHtmlReport : The input object cannot be bound to any parameters for the command either because the command
does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline
input.
At C:\Program Files\WindowsPowerShell\Modules\ATAPAuditor\ATAPAuditor.psm1:587 char:12
+ ...   $report | Get-ATAPHtmlReport -Path $Path -RiskScore:$RiskScore -has ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ATAPHtmlReport], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Get-ATAPHtmlReport

**Comment by TuemmlerKelch** [comment]
@RackAmpS Could you please tell me which Version you have been using?
Was it 5.5 / 5.6 prerelease / 5.6 official release?
Also, if you could recreate it, please upload a screenshot (don't forget to obfuscate relevant data)

**Comment by RackAmpS** [comment]
@TuemmlerKelch  I'm using the 5.5 release

![2023-09-25 12_45_20](https://github.com/fbprogmbh/Audit-Test-Automation/assets/26865345/9b1d2804-e269-4b6c-9300-1a6ed4a5a05a)
