### ISSUE TITLE
PowerShell from ms store fails when calling Get-Windowsoptionalfeature

### ISSUE THREAD

**Issue by SteffenWinternheimer** [fbprogmbh/Audit-Test-Automation#411]
There is an issue with Windows PowerShell being offered by MS store right now: Get-WindowsOptionalFeature -Online fails on 7.1.0-rc.2 (MSIX)- [Get-WindowsOptionalFeature: Class not registered]

![MicrosoftTeams-image](https://github.com/fbprogmbh/Audit-Test-Automation/assets/68649859/8a92d74e-4a47-48e4-8b4c-4b9c390802fd)

As MS has not fixed this in the last few months, we should implement a workaround to cope for this by importing DISM:
https://github.com/PowerShell/PowerShell/issues/13866#issuecomment-1519066710

**Comment by SteffenWinternheimer** [comment]
We move from using "Get-WindowsOptionalFeature" to DISM. Reason is that DISM is also supported on PowerShell Version 7. All occurences of Get-WindowsOptionalFeature will be replaced with "dism /Online /Get-Features".

Here is an example:
![grafik](https://github.com/fbprogmbh/Audit-Test-Automation/assets/35689334/6303b2be-d3af-4e6a-86c0-7d23bce915d7)

**Comment by TuemmlerKelch** [comment]
Please provide a list of unclear commands, I will provide the proper checks

**Comment by SteffenWinternheimer** [comment]
We only support PowerShell version 5.X
