### ISSUE TITLE
Server 2016 Audit 1.1.2 Ensure 'Maximum password age' is set to '60 or fewer days, but not 0'

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#42]
CIS Benchmark requires that value is to number of days.
Audit checks for seconds value.

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/a859964f5af25413514114b43852c021af98a429
