### ISSUE TITLE
Server 2016 Audit 1.1.3 Ensure 'Minimum password age' is set to '1 or more day(s)'

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#43]
CIS Benchmark requires that value is set to number of days.
Audit checks for number of seconds value.

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/a859964f5af25413514114b43852c021af98a429

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/a859964f5af25413514114b43852c021af98a429
