### ISSUE TITLE
Server-2016 report creation fails

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#434]
![image](https://github.com/fbprogmbh/Audit-Test-Automation/assets/68649859/038c9612-375a-4592-bdf3-d30f3a1de7e3)

**Comment by qngngyn** [comment]
Bug is found in line 1172 in Win Server 16 userrights. Fix will follow soon.

**Comment by flobroeder** [comment]
Received feedback that issue persists - need to investigate it further @SteffenWinternheimer

**Comment by TuemmlerKelch** [comment]
Could not reproduce, marking this as invalid until proven otherwise.
Will close this on November 13th

**Comment by TuemmlerKelch** [comment]
This issue was fixed in 5.6.3. The person that informed us about this issue was still using 5.6.2
