### ISSUE TITLE
Server 2016 Audit 1.1.5 Ensure 'Password must meet complexity requirements' is set to 'Enabled'

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#44]
CIS Benchmark requires that value is set to "Enabled"
Audit checks if value is "True"

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/a859964f5af25413514114b43852c021af98a429
