### ISSUE TITLE
"Get-SmbServerConfiguration"-Checks fail in some scenarios

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#443]
In contrast to below error message, the error is not related to filename-length.
Affected systems seem to be able to process these commands as soon as the "lanmanserver"-service is activated. However, this seems to be only part of the issue, as a lot of systems can still process these commands with lanmanserver being disabled.

![image](https://github.com/fbprogmbh/Audit-Test-Automation/assets/68649859/0a6aac9f-3274-4468-88c4-dea78aae2108)

**Comment by TuemmlerKelch** [comment]
suggestions:

|old|new|
|-|-|
|Microsoft|MS (for OS part, not Baseline publisher)|
|Restricted Traffic Limited Functionality|RTLF|
|Domain Controller|DC|

**Comment by qngngyn** [comment]
Current status is found in branch #443. The changed filenames do not fix the issue of Get-SmbServerConfiguration: Filename too long.

Suggestion: Run Get-SMbServerConfiguration -ErrorAction Stop to enable catching of errors, and proceeding the test with registry keys.

**Comment by TuemmlerKelch** [comment]
Please add a note when fallback is used and set status to warning:
*Get-SMBServerConfiguration failed, resorted to checking registry, which might not be 100% accurate. See [here](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/overview-server-message-block-signing#policy-locations-for-smb-signing) and [here](https://techcommunity.microsoft.com/t5/storage-at-microsoft/smb-signing-required-by-default-in-windows-insider/ba-p/3831704)
