### ISSUE TITLE
Refinement for Ubuntu 22.04 AuditGroup

### ISSUE THREAD

**Issue by svenschrader** [fbprogmbh/Audit-Test-Automation#446]
AuditGroup "Ubuntu 22.04" has still some minor issues, e.g. errors on PowerShell, or bash level, and some false-negatives (showing as non-compliant although correct)

In addition, all Shell scripts CIS-Ubuntu22.04_LTS-*.sh should go into an appropriate subdirectory

**Comment by RAW0611** [comment]
@svenschrader the branch to this issue still exists. There is also no PR linked. Please consider deleting the branch.
