### ISSUE TITLE
Server 2016 Audit 1.1.6 Ensure 'Store passwords using reversible encryption' is set to 'Disabled'

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#45]
CIS Benchmark requires that value is set to "Disabled"
Audit checks if value is "False"

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/a859964f5af25413514114b43852c021af98a429
