### ISSUE TITLE
Update Windows 10 Stand-alone audit groups to 2.0.0

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#468]
as the title suggests, please do the update

**Comment by TuemmlerKelch** [comment]
@SteffenWinternheimer Please make sure to delete old audit groups, when updating to a new version.

**Comment by SteffenWinternheimer** [comment]
@TuemmlerKelch I just deleted the older audit groups, you can review the ticket again.

**Comment by TuemmlerKelch** [comment]
Deleted old audit groups and updated to 2.0.0
