### ISSUE TITLE
Server 2016 Audit 1.2.3 Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#47]
CIS Benchmark requires that value is set to number of minutes.
Audit checks for number of seconds value.

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/a859964f5af25413514114b43852c021af98a429
