### ISSUE TITLE
Server 2016 Advanced Audit Policy Configuration 

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#48]
On a german system, Audit TAP needs also to check for "Erfolg, Erfolg und Fehler and Keine Überwachung"
For all settings, Audit TAP could not get setting.

**Comment by PatHelb** [comment]
Added in https://github.com/fbprogmbh/Audit-Test-Automation/commit/763448504afb34575791f476a765c26bd3ade412
