### ISSUE TITLE
SQL 2016 2.11 Ensure SQL Server is configured to use non-standard ports

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#49]
Audit TAP seems to have a problem with named Instances.
Error message: Server Instance not found or accessible.

**Comment by PatHelb** [comment]
Fixed in https://github.com/fbprogmbh/Audit-Test-Automation/commit/bdb2059e03003ae07d8b0851c385dc63ed397f7e
