### ISSUE TITLE
IIS10Audit usage after installing the module

### ISSUE THREAD

**Issue by eliassal** [fbprogmbh/Audit-Test-Automation#502]
Hi, I installed the module as follows
`Install-Module -Name IIS10Audit`
as well as 
`Install-Module -Name ATAPAuditor`
Can you please let me know ho can I start an IIS audit? or how can I get to arguments for commandline?

Thanks in advance

**Comment by TuemmlerKelch** [comment]
Hi @eliassal,
thx for bringing IIS10Audit back to our attention, this is deprecated and has been replaced by the IIS-Check within ATAP Auditor.
To create an IIS-Report, enter the following command in an administrative PowerShell Session:
`Save-ATAPHtmlReport -ReportName "Microsoft IIS10"`

**Comment by eliassal** [comment]
So many thanks, yes it works like a charm and audit report is great help. I think maybe that your usage page might \need some updates :-)
So I can remove safely the module IIS10Audit? Thanks again for your help.
N.B: All your videos are in German language on Youtube, is there any English videos?
