### ISSUE TITLE
CIS Windows 10 Stand-alone 2.0.0 RefIDs mismatch

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#509]
One example:
correct: 18.9.35.2
wrong: 18.8.37.2

Please do a comparison ATAP vs original documentation

**Comment by SteffenWinternheimer** [comment]
@TuemmlerKelch, I have checked this rule, it seems like it is actually correct, are you sure you meant the right one?

**Comment by SteffenWinternheimer** [comment]
Issue closed. CIS is in the making of Benchmark in version 3.0.0.

**Comment by TuemmlerKelch** [comment]
As CIS will soon release their 3.0.0 benchmark for Windows 10 Stand-alone systems, we will not put further effort into this.
