### ISSUE TITLE
Credential Guard is configured but not running depending on OS SKU (SBD-021)

### ISSUE THREAD

**Issue by phfriedrich** [fbprogmbh/Audit-Test-Automation#556]
## **_System_**
| Information | Content |
|:--------:|:--------:|
| OS | Windows 11 Business |
| Build | Version 22H2 (Build 22621.3447) |
| Architecture | 64-bit |
| License Status | Licensed | 

## **_Status_**
AuditTest Id "SBD-021" checks if Credential Guard is running on the system. 
`(Get-CimInstance -ClassName Win32_DeviceGuard -Namespace root\Microsoft\Windows\DeviceGuard).SecurityServicesRunning -contains 1`

Depending on the SKU used on the system, Credential Guard may be configured but not running due to licensing.
AuditTAP checks if the service is running and marks the setting as non-compliant.

## **_Expected_**
Credential Guard is supported in the following SKUs:
| Windows Pro | Windows Enterprise | Windows Pro Education/SE | Windows Education |
| -- | -- | -- | -- |
| No | Yes | No | Yes |

When running the checks for Credential Guard, we should check if one of the SKUs mentioned above is installed on the system.
If yes, we can execute the same checks as we do now. 

However, if another SKU is installed, we can check for the configuration instead. 
If the configuration has not been made, AuditTAP should still mark the setting as False (non-compliant). 
If Credential Guard is configured, but not running, AuditTAP should give this information to the user. 
`(Get-CimInstance -ClassName Win32_DeviceGuard -Namespace root\Microsoft\Windows\DeviceGuard).SecurityServicesConfigured -contains 1`

## **_Output_**
False
Info: Credential Guard is configured but not running, due to incompatibility with %OS% (Windows 11) %SKU% (Business)

**Comment by TuemmlerKelch** [comment]
Tested on W10 Enterprise, Server 2026 and 2022
