### ISSUE TITLE
Issue with AuditTAP When Changing PowerShell Security Rule to ConstrainedLanguage

### ISSUE THREAD

**Issue by PfeilImKopf** [fbprogmbh/Audit-Test-Automation#568]
### Operating System

Windows 10

### Report Name

Microsoft Windows 10

### Benchmark and ID (OPTIONAL)

Security Base Data : SBD-025

### What happened?

1. When the LanguageMode of PowerShell ist set to ConstrainedLanguage, the ATAP is not executable! The Import of the modules throws multiple errors 
![20240426_222231](https://github.com/fbprogmbh/Audit-Test-Automation/assets/33699684/0f8ee1c4-20df-49cf-946c-121b8b170dd9)
2. The check on the languageMode is testing on the string "Constrained Language" instead of "ConstrainedLanguage". Not important if the ATAP is not being executable because of this rule

### What did you expect?

ATAP starting as intended! giving proper feedback about this configuration

### Current Version?

I used the latest official release.

**Comment by TuemmlerKelch** [comment]
Please implement the following if possible:

1. Add a check for language mode
2. If constrained language mode, inform the user about that fact and inform that ATAP requires FullLanguage mode. Ask if user wants to activate FullLanguage over the course of ATAP being executed
2.1 If user allows FullLanguage continue
2.2 If user does not allow, cancel script with necessary information
3. After ATAP has finished, revert back to whatever Language mode was active beforehands

If changing back and forth is not possible, just end script informing user that ATAP requires Full Language and needs to be configured appropriately if user desires to utilize ATAP

**Comment by qngngyn** [comment]
I have learned that changing modes within the same session does not work when changing from "ConstrainedLanguage" -> "FullLanguage". Alternative solution would be to add on how to handle this in our FAQ, and add a solution to the FAQ.
