### ISSUE TITLE
Error message appears when running IIS10-Report when IISAdministration-Module not available

### ISSUE THREAD

**Issue by SteffenWinternheimer** [fbprogmbh/Audit-Test-Automation#585]
### Operating System

Windows 10

### Report Name

Microsoft IIS10

### What happened?

When running IIS10 report without having IIS10 installed, the following error message appears:
![grafik](https://github.com/fbprogmbh/Audit-Test-Automation/assets/35689334/503f2424-d1a6-4181-aa1b-aeb872bde820)

### What did you expect?

This error should be catched.

### Current Version?

I used the latest official release.

**Comment by qngngyn** [comment]
moving check next to "start-module" checks. implementation lgtm.
