### ISSUE TITLE
Report generation freezes for Audit RHEL 8

### ISSUE THREAD

**Issue by swiedernix** [fbprogmbh/Audit-Test-Automation#588]
### Description

I get the following error on RHEL8, I have installed ATAPAuditor/ATAPHtmlReport using PS Gallery

PS /root> Save-ATAPHtmlReport -ReportName .\"Red Hat Enterprise Linux 8" -RiskScore -Path /tmp
Test-AuditGroup: /root/.local/share/powershell/Modules/ATAPAuditor/5.9.0/Reports/Red Hat Enterprise Linux 8.ps1:14
Line |
  14 |  …              AuditInfos = Test-AuditGroup "SBD - Linux Base Security"
     |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'tpm2_getcap' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

    Directory: /tmp

UnixMode         User Group         LastWriteTime         Size Name
--------         ---- -----         -------------         ---- ----
-rw-r--r--       root root         5/7/2024 14:04       116349 Red Hat Enterprise Linux 8 Report_20240507_140450.html

PS /root>
PS /root> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Red Hat Enterprise Linux 8.9 (Ootpa)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by svenschrader** [comment]
Red Hat Audit Group is currently being finalized in ticket #490 
See branch ticket_490, feel free to run the script from that branch. The freeze should not happen anymore

**Comment by TuemmlerKelch** [comment]
@swiedernix Have you been able to generate a report with above mentioned [fix version?](https://github.com/fbprogmbh/Audit-Test-Automation/archive/refs/heads/ticket_490.zip)

**Comment by svenschrader** [comment]
Issue is resolved after #490  has been merged. This the new audit group provides CIS Red Hat Benchmark 9, so 8 is obsolete
