### ISSUE TITLE
When printing HTML to PDF color schema gets lost

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#59]
See title 

![image](https://user-images.githubusercontent.com/23223285/91071264-4184ca00-e638-11ea-9462-104020271af8.png)

**Comment by TuemmlerKelch** [comment]
This is actually not an issue, but a feature to save ink (which obviously does not make sense in case of printing to PDF). To keep formatting, make sure to check the "print backgrounds" option, as shown in below screenshot from Firefox. It might have a slightly different name in other browsers.
![image](https://user-images.githubusercontent.com/68649859/181188793-cbdcd653-efa9-4626-a66b-75a80366caa6.png)
