### ISSUE TITLE
Request: Check new LAPS Group POlicy path

### ISSUE THREAD

**Issue by genauder** [fbprogmbh/Audit-Test-Automation#592]
### Description

Since last year LAPS is an integrated component of Windows. Microsoft changed the Group Policy path to:

"Computer Configuration\Policies\Administrative Templates**\System\**LAPS\"

It seems that AuditTAB is just checking the old path which is "Computer Configuration\Policies\Administrative Templates\LAPS\".

So I am kindly asking you to update ATAPAuditor to recognize and check the new path.

Thanks!

### What are the benefits?

Correct report since Microsoft recommends to use the new GP path.

### Acceptance Criteria!

Report checks and recognizes settings in the new path.

**Comment by TuemmlerKelch** [comment]
That's correct. CIS regards this change with their 3.0.0 series of Benchmarks.
Currently, the only report to feature this change is Windows 11 Report.
Windows 10 Report can already be found in our acceptance branch and will be published with Release 5.10.
Windows Servers 2016,19,22 will follow, but probably in a later release.

As we are already aware of this and the necessary issues have been created, I will close this issue.

So, if you need a Windows 11 report, use 5.9.0; if you need a Windows 10 report, download current approve branch.
If you need a Report for Server 2016+, I suggest running a Windows 11 report and looking at LAPS section to get your result for now.

Feel free to get back to us.
