### ISSUE TITLE
Incorrect Registry-Path for 18.9.19.5

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#594]
### Operating System

Windows 11

### Report Name

Microsoft Windows 11

### Benchmark and ID (OPTIONAL)

CIS W10/W11 Benchmark 3.0.0 // 18.9.19.5

### What happened?

/SOFTWARE/ was missing from reg path

Wrong: HKEY_LOCAL_MACHINE\Policies\...
Correct: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\...

### What did you expect?

correct implementation ;)

### Current Version?

I used the latest prerelease version.

**Comment by SteffenWinternheimer** [comment]
Created PR for this ticket, waiting for response.
