### ISSUE TITLE
Incorrect numbering of SBD-rules

### ISSUE THREAD

**Issue by PfeilImKopf** [fbprogmbh/Audit-Test-Automation#597]
### Operating System

Windows 11

### Report Name

Microsoft Windows 11

### Benchmark and ID (OPTIONAL)

SBD-073

### What happened?

Rule SBD-073 does not exist. Probably skipped!
![image](https://github.com/fbprogmbh/Audit-Test-Automation/assets/33699684/39c3cefe-77e6-4879-af0b-a34a9393d1cf)

### What did you expect?

An existing rule SBD-073

### Current Version?

I used the latest official release.

**Comment by TuemmlerKelch** [comment]
Every section should get its own number range. Let's discuss this.
