### ISSUE TITLE
Microsoft Windows 10 BSI Report does not check BSI SiSyPHus Recommendations for Stand alone systems

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#598]
### Operating System

Microsoft Windows 10 Stand-alone

### Report Name

Microsoft Windows 10 BSI

### What happened?

Due to missing check, standalone systems are not audited against the appropriate baseline:
https://github.com/fbprogmbh/Audit-Test-Automation/blob/master/ATAPAuditor/Reports/Microsoft%20Windows%2010%20BSI.ps1#L38

(This also affects Windows 11 Report: https://github.com/fbprogmbh/Audit-Test-Automation/blob/master/ATAPAuditor/Reports/Microsoft%20Windows%2011.ps1#L92)

### What did you expect?

In case the system is not domain integrated, NE Report should be run.

### Current Version?

I used the latest official release.

**Comment by TuemmlerKelch** [comment]
@SteffenWinternheimer Please check how much effort this would be and decide if we implement this with 5.10 or 5.11

**Comment by SteffenWinternheimer** [comment]
Ticket merged into approve branch
