### ISSUE TITLE
Suggest opening the report after creation

### ISSUE THREAD

**Issue by qngngyn** [fbprogmbh/Audit-Test-Automation#609]
### Description

It should prove useful to open the report after creation right away.

### What are the benefits?

More userability.

### Acceptance Criteria!

Prompt on whether you want to open a report after creation and do so when "yes".

**Comment by TuemmlerKelch** [comment]
Due to the fact, that the spawned process will be started as the user you are logged in to the OS, this breaks for elevated sessions that run in the context of a different user.
