### ISSUE TITLE
Support of IIS 10 1.1.1 and IIS 8 1.5.0 ?

### ISSUE THREAD

**Issue by Melmann** [fbprogmbh/Audit-Test-Automation#61]
Hi,

I just want to know if you plan to add the support of others IIS CIS like IIS 10 1.1.1 and IIS 8 1.5.0 ?

Thanks in advance,

Quentin

**Comment by flobroeder** [comment]
Dear Quentin, thanks for your question. 
the Audit TAP is our "free of charge" product and we try to update whenever it fits in our time schedule. I doubt that we will include "older" standards. Maybe interesting for you: We offer more hardening benchmarks beneath CIS and corresponding audit functions in our official toolset/product "Enforce Administrator". 
More information? 
English here: https://www.fb-pro.com/wp-content/uploads/2020/02/EnforceSuite_overview_long_EN.pdf
German here: https://www.fb-pro.com/enforce-suite/

Kind regards,
Florian
