### ISSUE TITLE
Australian Security standard not clear at some points

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#62]
![scr1_australian_gleicher_text](https://user-images.githubusercontent.com/23223285/111818613-ab6c0600-88df-11eb-9a19-c777cf9d7105.PNG)

Same text at some controls - please clarify if this can be changed.

**Comment by PatHelb** [comment]
We have a look at this, but it is not clarified by the australian cyber security centre. Maybe we change this manually but not yet

**Comment by TuemmlerKelch** [comment]
Fixed with ATAP version 5.1
