### ISSUE TITLE
Wrong Reference in baseline list

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#630]
### Operating System

Windows 11

### Report Name

Microsoft Windows 11

### What happened?

Created Windows 11 report with current 5.10 preRelease, while the correct benchmar (v1.2.1) was tested, the list states "FB Pro recommendations 'Ciphers Protocols and Hashes Benchmark', Version 1.1.0, Date: 2021-04-15"

### What did you expect?

Correct mention of FB Pro recommendations 'Ciphers Protocols and Hashes Benchmark', Version 1.2.1

**Please make sure to check all other reports, too**

### Current Version?

I used the latest prerelease version.

**Comment by SteffenWinternheimer** [comment]
Information adjusted. Ticket will be closed now. (Due to the release, i did the changes on the approve branch directly.)
