### ISSUE TITLE
Incomplete sentence in README

### ISSUE THREAD

**Issue by joel-mrtn** [fbprogmbh/Audit-Test-Automation#632]
### Operating System

Windows 11

### Report Name

Microsoft Windows 11

### What happened?

It's not a coding bug, but a minor error in the first sentence of the section "How to install" in the README.md file. The sentence is missing something at the end.

> We offer several ways of how you can use our free of charge **[?]**.

### What did you expect?

Maybe add the name of the tool at the end. Here is an alternative:

> We offer several ways to use our free of charge Audit Test Automation Package.

... or something like that :)

### Current Version?

I used the latest official release.

**Comment by TuemmlerKelch** [comment]
@joel-mrtn Thanks for bringing this to our attention. We will rewrite that section.
