### ISSUE TITLE
Several reg keys not found and explanation text not clear

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#64]
![image](https://user-images.githubusercontent.com/23223285/111870363-97c6ab00-8984-11eb-891e-00695f957f77.png)

Firewall is enabled on test system.
Differentiation between different tests not clear.

**Comment by PatHelb** [comment]
these means the various registry settings for domain, private and public firewall profiles. And stands for the specific registry keys

**Comment by TuemmlerKelch** [comment]
> these means the various registry settings for domain, private and public firewall profiles. And stands for the specific registry keys

Thank you for explaining. However this should be clearly described within the Report itself. I checked 4.14 and this was not yet updated.

**Comment by TuemmlerKelch** [comment]
Fixed with ATAP 5.1
