### ISSUE TITLE
If report exists no status message at the end of reporting is created - report is saved in any case

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#68]
![image](https://user-images.githubusercontent.com/23223285/122401387-d583a180-cf7c-11eb-90da-2dd9f43f710a.png)

Steps to reproduce: 

1) Save-ATAPHTMLReport
2) DIrectly after create another one with same file name

New one is saved although error message appears.

**Comment by flobroeder** [comment]
It is about Release 4.12 RC 1

**Comment by SteffenWinternheimer** [comment]
Issue FIXED - Report  .html now is more precise in the title 

e.g. Microsoft Windows 10 BSI_20210618_133316.html
The number in the title stands for:
2021 - year
06 - month
18 - day
13 - hour
33 - minute
16 - seconds

**Comment by SteffenWinternheimer** [comment]
optimized transparence if case report file already exists. Console will print a warning message, if file already exists
