### ISSUE TITLE
Errors in AuditTAP creation when using german Windows 7 with installed english language pack

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#72]
As above mentioned from Teal Technology Consulting Audit TAP produces errors. 
Please try to reproduce / investigate.

**Comment by SteffenWinternheimer** [comment]
I have set up a new Windows 2019 Server and installed AuditTAP's latest version and executed the "Microsoft Windows 2019 Server DC". Seemed to work. Try to download the lastest version and give it another try.

![Server Report AuditTAP](https://user-images.githubusercontent.com/35689334/127285610-3342a486-f8b3-4fc6-8d25-680d6893c841.PNG)

**Comment by TuemmlerKelch** [comment]
Due to this being over a year old, we won't put any more effort into this. Fixed multiple issues, probably this one is already fixed, too.
