### ISSUE TITLE
In console view several errors occur and are displayed - Audit TAP creates report anyway

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#73]
As shown in screenshot AuditTAP creates several errors in console view - report is generated anyway. 
Is this critical? Why do these errors occur? Can this be fixed? 

![image](https://user-images.githubusercontent.com/23223285/126769947-eb6a7e89-bcd5-4d04-a26a-40b1cca61f83.png)

**Comment by unterzahl** [comment]
In addition we had an error when TAP wants to check fireforx settings, but firefox is not installed.... 
May Tap can check if the product is really installed on the target system...

**Comment by SteffenWinternheimer** [comment]
Hey. I set up a new Microsoft Windows 2019 Server and installed the latest Version of AuditTAP. Seemed to work without any problems. Maybe you have an older version of the AuditTAP.

![Server Report AuditTAP](https://user-images.githubusercontent.com/35689334/127285939-52f7b922-be6a-476a-86c6-9319613caaa2.PNG)

**Comment by SteffenWinternheimer** [comment]
I tried the same with report "Microsoft Windows Server 2019". Works as well.

![Server Report AuditTAP Default](https://user-images.githubusercontent.com/35689334/127286721-f7db9541-7859-4a00-b897-d6f11f0ea6ab.PNG)
