### ISSUE TITLE
Import-Module throws New-Alias not allowed

### ISSUE THREAD

**Issue by T3Bzg** [fbprogmbh/Audit-Test-Automation#74]
```Import-Module -Name .\ATAPAuditor\ATAPAuditor.psm1 -Force``` 
throws "The alias ist not allowed", see screenshot. Bug seemed fixed in TEAL fork, but I have no idea why.
![TAPshrBug](https://user-images.githubusercontent.com/84328187/127306870-14ba9a66-ba57-4273-9252-5a99913a948e.PNG)

**Comment by SteffenWinternheimer** [comment]
the problem occurs if the corresponding module is imported with "Import-Module ATAPAuditor" before. Open a new PowerShell and execute the command before an "Import-Module ATAPAuditor" is executed. A new session solves the problem.
Of course the module can also be imported by name of the .psm1 script.
