### ISSUE TITLE
CIS benchmark allows "Medium or lower" but only medium is allowed in the script.

### ISSUE THREAD

**Issue by SteffenWinternheimer** [fbprogmbh/Audit-Test-Automation#78]
https://github.com/fbprogmbh/Audit-Test-Automation/issues/76#issuecomment-947553316

**Comment by TuemmlerKelch** [comment]
According to CIS, there are 5 different levels of trust:
Full, High, Medium, Low, and Minimal.
--> Following CIS logic, everything other than Full or High should result in a positive result.

**Comment by TuemmlerKelch** [comment]
Added low and minimal

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed with commit e1121195e8c7efdd7d4e1fbb06fd2ce3eead111e
