### ISSUE TITLE
Check report path right before testing

### ISSUE THREAD

**Issue by devesly** [fbprogmbh/Audit-Test-Automation#8]
Check the passed path right before starting all test function otherwise tests are done unnecessarily because report cannot be written to desired destination.
As in a bigger environment the report cmdlet could take up to 45 minutes or more to finish, checking the path as a first step could be a huge time saver.

**Comment by devesly** [comment]
```powershell
function Get-WindowsServer2016HtmlReport {
	param (
		[string] $Path = "$($env:HOMEPATH)\Documents\$(Get-Date -UFormat %Y%m%d_%H%M)_auditreport.html",

		[switch] $DarkMode,

		[switch] $PerformanceOptimized
	)

	if (Test-Path $Path) {
```

Test-Path with standard path will always fail because the html file is not created  at this point

**Comment by Beneboe** [comment]
This needs to be implemented not just in WindowsServer2016Audit, but all audits.
