### ISSUE TITLE
Save-ATAPHtmlReport for "Microsoft IIS10" generates same HTML content with new file name, unless new PowerShell window open

### ISSUE THREAD

**Issue by SergGu** [fbprogmbh/Audit-Test-Automation#80]
Hello 

I noticed some odd bug with HTML staying the same, even when new files are getting generated. I tested in two environments, on two machines with different build and hardening, therefore probably not the environment-specific. Only when the PowerShell window is closed and started, HTML gets refreshed and the report shows new results.

When running the Test-Tune-Test sequence, the tool generates SAME reports and ignore any tuning and just made changes in IIS settings. The workaround is to close the PowerShell window and start again. While at the same time individual PowerShell commands are able to reflect newly made changes. The timestamp inside the HTML file is correct (does refresh) but no other content.

Below are the steps to reproduce this:

# PS window - "initial" report, keep this window open
Save-ATAPHtmlReport -ReportName "Microsoft IIS10" -Force
# CMD window - add trace filter CIS , alternatively changes can me mage in IIS GUI
%systemroot%\system32\inetsrv\appcmd set config /section:requestfiltering /+verbs.[verb='TRACE',allowed='false']
# PS window - "after change" report
Save-ATAPHtmlReport -ReportName "Microsoft IIS10" -Force
# resulting HTML file do not pick changes !!! 
# close and start new PS window
# in new PS window
Save-ATAPHtmlReport -ReportName "Microsoft IIS10" -Force
# Now I can see the settings changed.

# CMD - cleanup - removal of settings, note minus:
%systemroot%\system32\inetsrv\appcmd set config /section:requestfiltering /-verbs.[verb='TRACE',allowed='false']

Regards,
Serg

P.S. This is a great tool for auditing IIS servers. It is better than some other commercial products we have in our arsenal.

**Comment by SteffenWinternheimer** [comment]
Hello!
Thank you very much for the detailed description of the problem. We appreciate it that our tool is gladly used for overview purposes. 
I will replicate the issue and try to get it fixed for the next release.

**Comment by SteffenWinternheimer** [comment]
This issue has been fixed in this preview of PreRelease 4.14: https://github.com/fbprogmbh/Audit-Test-Automation/releases/tag/v4.14-preview1
