### ISSUE TITLE
Missing blank in Audit Report

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#81]
![image](https://user-images.githubusercontent.com/23223285/145633045-e035d157-d8e3-42a7-8f58-319b6e3e3897.png)

**Comment by SteffenWinternheimer** [comment]
Has been fixed in PreRelease 4.14:
https://github.com/fbprogmbh/Audit-Test-Automation/releases/tag/v4.14-preview3
