### ISSUE TITLE
Check validation logic of BSI benchmark ID 100 -- Ensure 'Turn off automatic learning' is set to 'Enabled'.

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#82]
Please check validation logic - in case settings RestrictImplicitInkCollection and RestrictImplicitTextCollection is set to "0" in Registry setting is compliant...in case both settings are set to "1" the setting is "non compliant"...

Exptected is the opposite beahviour following this article: 
https://appuals.com/disable-automatic-learning-in-windows-10/#:~:text=%20Method%201%3A%20Disabling%20Automatic%20Learning%20through%20Local,automatic%20learning%20%E2%80%9C.%20This%20will%20open...%20More%20

**Comment by SteffenWinternheimer** [comment]
Has been fixed in PreRelease 4.14:
https://github.com/fbprogmbh/Audit-Test-Automation/releases/tag/v4.14-preview3
