### ISSUE TITLE
Enterprise version of Windows 10 is not checked - all tests are executed "equally"

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#83]
Using WIndows 10 enterprise and the following is documented: 

![image](https://user-images.githubusercontent.com/23223285/145715610-6f8ac9b5-8685-4e4a-af9c-e47f76b48bdf.png)

Expected behaviour: Should check if Windows 10 is "Enterprise" version - then execute "Enterprise" check, If not execute the other one...
For example this can be checked...
(Get-WmiObject -class Win32_OperatingSystem).Caption

**Comment by SteffenWinternheimer** [comment]
Has been fixed in PreRelease 4.14:
 https://github.com/fbprogmbh/Audit-Test-Automation/releases/tag/v4.14-preview3
