### ISSUE TITLE
Error in BSI-Check for German OS

### ISSUE THREAD

**Issue by schmmax** [fbprogmbh/Audit-Test-Automation#88]
After Hardening with BSI on a germane OS, the User Anonymous-Anmeldung is present in SeDenyRemoteInteractiveLogonRight, however Audit-TAP is searching for Anonymous-Logon.
See Screenshot.
![Audit TAP Error](https://user-images.githubusercontent.com/56861310/146565797-ac1afcda-8b4b-445c-9804-82badde14ab0.JPG)

**Comment by flobroeder** [comment]
seems to be a translation issue...
@Steffen: Assigned it to you, can you please take care for it? 
Thanks!

**Comment by SteffenWinternheimer** [comment]
Reason is that users are compared by their string, not by their SIDs. This is now fixed in 9e08c5aaa499ceb04344e670903da819ccaae17d
