### ISSUE TITLE
Server 2016 audit shows "Found member(s)"  for null

### ISSUE THREAD

**Issue by devesly** [fbprogmbh/Audit-Test-Automation#9]
In a test environment the Windows Server 2016 audit tap shows "Found member(s)" if a User Rights Assignment setting is configured with no group or user.

For example:
The User Rights Assignment "The Lock pages in memory user right must not be assigned to any groups or accounts" is configured via GPO and no group or user are added which would be compliant with DISA. Nevertheless the audit report flags red for this section.

Further rules: SV_88455r1_rule, SV_88443r1_rule, SV_88415r1_rule

**Comment by Beneboe** [comment]
Note: Corresponds to rules WN16-UR-000110, _WN16-MS-000420_, _WN16-UR-000250_.

fixed in restructuring 40b84f0cbed265b829d0cbe3e040bbafa1f9e2aa
