### ISSUE TITLE
System-role specific settings

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#92]
Currently, some DISA settings are configured to properly reflect the system not being a domain-joined system and regarding.
Example: WN19-MS-000030 -> Not applicable. This audit applies only to MemberServer. -> Status: NONE

However, this control is identical to CIS 18.8.28.4 and Microsoft Registry-033. Both of those state "Registry value not found" -> False

I believe CIS and MS controls should be changed to work like DISA.

Generally, I suggest checking the following and regarding this in the audit results:

- System domain-joined: yes
- System domain-joined: no
- System is DC

The following code will check the system-role and return a numeric value depending on the role:
`Get-Wmiobject -Class ‘Win32_computersystem’ -ComputerName $env:computername | Select-Object domainrole`

Value|Description
-- | --
0 | Standalone Workstation
1 | Member Workstation
2 | Standalone Server
3 | Member Server
4 | Backup Domain Controller
5 | Primary Domain Controller

Resulting configurations are:
domain-joined: 1,3,4,5
non-domain-joined: 0,2
Domain Controller: 4,5

**Comment by flobroeder** [comment]
Additional information - AuditTAP executed on **Member server** checks for settings only relevant for DomainControllers...
See attached screenshot...
Expected: This settings should not be checked - other settings in same report show message regarding this mismatch. 
Please check all settings trageting "DC only"...

![image](https://user-images.githubusercontent.com/23223285/168284203-b5f5e2a0-9024-4887-b1ae-1f3a5aa5e9ba.png)

**Comment by SteffenWinternheimer** [comment]
Issue has been fixed with commit [a2f9797](https://github.com/fbprogmbh/Audit-Test-Automation/commit/a2f97976f85413f2b0ebcff354823a0fc4146dbf)
