### ISSUE TITLE
Some related controls share descriptions > Change descriptions to reflect each control

### ISSUE THREAD

**Issue by TuemmlerKelch** [fbprogmbh/Audit-Test-Automation#93]
I have identified a few controls that share the descriptions making it hard to identify what exactly needs to be done.
Please see attached excel files for the controls I have identified so far and a proposol how to describe them.
I found them in Windows Server 2019 Reports, but I guess this is also present in other Reports.
[Controls.xlsx](https://github.com/fbprogmbh/Audit-Test-Automation/files/8169039/Controls.xlsx)

**Comment by SteffenWinternheimer** [comment]
Issue solved in commit a8384b71ecc75eba207f43c0bdd42f5d66eecf07
Thank you very much for this detailed comment :)
